[allowlist]
  regexTarget = "match"
  regexes = [
    '''your-p12-password''',
    '''your-api-token''',
    '''var\.f5xc_api_cert''',
    '''var\.f5xc_api_key''',
    '''var\.f5xc_p12_password''',
    '''secrets\.F5XC_''',
  ]
