// Copyright (c) 2026 Robin Mordasiewicz. MIT License.

package registration

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/f5xc-salesdemos/terraform-provider-xcsh/tools/pkg/openapi"
)

func TestCleanOrphanGeneratedFiles(t *testing.T) {
	// Create temp directories for provider and client files
	outDir := t.TempDir()
	clntDir := t.TempDir()

	doNotEdit := "// Code generated by generate-all-schemas.go. DO NOT EDIT.\npackage provider\n"
	manual := "// Manually maintained\npackage provider\n"

	// Create generated resource files
	os.WriteFile(filepath.Join(outDir, "active_resource.go"), []byte(doNotEdit), 0644)
	os.WriteFile(filepath.Join(outDir, "orphan_resource.go"), []byte(doNotEdit), 0644)
	os.WriteFile(filepath.Join(outDir, "manual_resource.go"), []byte(manual), 0644)

	// Create generated data source files
	os.WriteFile(filepath.Join(outDir, "active_data_source.go"), []byte(doNotEdit), 0644)
	os.WriteFile(filepath.Join(outDir, "orphan_data_source.go"), []byte(doNotEdit), 0644)

	// Create generated client type files
	os.WriteFile(filepath.Join(clntDir, "active_types.go"), []byte(doNotEdit), 0644)
	os.WriteFile(filepath.Join(clntDir, "orphan_types.go"), []byte(doNotEdit), 0644)

	// Create test files — orphan_resource_test.go has no matching resource
	os.WriteFile(filepath.Join(outDir, "active_resource_test.go"), []byte("package provider\n"), 0644)
	os.WriteFile(filepath.Join(outDir, "orphan_resource_test.go"), []byte("package provider\n"), 0644)

	// Create data source test file — orphan_data_source_test.go has no matching data source
	os.WriteFile(filepath.Join(outDir, "active_data_source_test.go"), []byte("package provider\n"), 0644)
	os.WriteFile(filepath.Join(outDir, "orphan_data_source_test.go"), []byte("package provider\n"), 0644)

	generatedNames := map[string]bool{
		"active": true,
	}

	CleanOrphanGeneratedFiles(outDir, clntDir, generatedNames)

	// Verify: active files should still exist
	for _, f := range []string{
		filepath.Join(outDir, "active_resource.go"),
		filepath.Join(outDir, "active_data_source.go"),
		filepath.Join(outDir, "active_resource_test.go"),
		filepath.Join(outDir, "active_data_source_test.go"),
		filepath.Join(clntDir, "active_types.go"),
	} {
		if _, err := os.Stat(f); os.IsNotExist(err) {
			t.Errorf("expected active file to exist: %s", filepath.Base(f))
		}
	}

	// Verify: orphan generated files should be removed
	for _, f := range []string{
		filepath.Join(outDir, "orphan_resource.go"),
		filepath.Join(outDir, "orphan_data_source.go"),
		filepath.Join(clntDir, "orphan_types.go"),
	} {
		if _, err := os.Stat(f); !os.IsNotExist(err) {
			t.Errorf("expected orphan file to be removed: %s", filepath.Base(f))
		}
	}

	// Verify: orphan test files should be removed (no matching resource/data source)
	for _, f := range []string{
		filepath.Join(outDir, "orphan_resource_test.go"),
		filepath.Join(outDir, "orphan_data_source_test.go"),
	} {
		if _, err := os.Stat(f); !os.IsNotExist(err) {
			t.Errorf("expected orphan test file to be removed: %s", filepath.Base(f))
		}
	}

	// Verify: manually maintained file should NOT be removed
	if _, err := os.Stat(filepath.Join(outDir, "manual_resource.go")); os.IsNotExist(err) {
		t.Error("expected manually maintained file to be preserved")
	}
}

func TestCleanOrphanGeneratedFiles_EmptyDirs(t *testing.T) {
	outDir := t.TempDir()
	clntDir := t.TempDir()

	// Should not panic on empty directories
	CleanOrphanGeneratedFiles(outDir, clntDir, map[string]bool{})
}

func TestGenerateProviderRegistration(t *testing.T) {
	outDir := t.TempDir()

	results := []openapi.GenerationResult{
		{ResourceName: "http_loadbalancer", Success: true, AttrCount: 5, BlockCount: 2},
		{ResourceName: "origin_pool", Success: true, AttrCount: 3, BlockCount: 1},
		{ResourceName: "failed_resource", Success: false, Error: "something went wrong"},
	}

	GenerateProviderRegistration(results, outDir)

	providerPath := filepath.Join(outDir, "provider.go")
	content, err := os.ReadFile(providerPath)
	if err != nil {
		t.Fatalf("provider.go was not created: %v", err)
	}

	contentStr := string(content)

	// Should contain the DO NOT EDIT header
	if !contains(contentStr, "DO NOT EDIT") {
		t.Error("expected DO NOT EDIT header in provider.go")
	}

	// Should contain resource registrations for successful resources
	// naming.ToResourceTypeName: "http_loadbalancer" -> "HTTPLoadBalancer"
	if !contains(contentStr, "NewHTTPLoadBalancerResource") {
		t.Error("expected NewHTTPLoadBalancerResource in provider.go")
	}
	if !contains(contentStr, "NewOriginPoolResource") {
		t.Error("expected NewOriginPoolResource in provider.go")
	}

	// Should contain data source registrations
	if !contains(contentStr, "NewHTTPLoadBalancerDataSource") {
		t.Error("expected NewHTTPLoadBalancerDataSource in provider.go")
	}

	// Should NOT contain failed resource
	if contains(contentStr, "NewFailedResourceResource") {
		t.Error("did not expect NewFailedResourceResource in provider.go")
	}
}

func TestGenerateCombinedClientTypes(t *testing.T) {
	// Verify it doesn't panic (it's a no-op)
	results := []openapi.GenerationResult{
		{ResourceName: "test", Success: true},
	}
	GenerateCombinedClientTypes(results, t.TempDir())
}

func TestCoreResourcesDefault(t *testing.T) {
	if len(CoreResources) != 0 {
		t.Errorf("expected CoreResources to be empty, got %d entries", len(CoreResources))
	}
}

func contains(s, substr string) bool {
	return len(s) > 0 && len(substr) > 0 && containsSubstring(s, substr)
}

func containsSubstring(s, substr string) bool {
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			return true
		}
	}
	return false
}
