// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package client

import (
	"context"
	"fmt"
)

// ApplicationProfiles represents a F5XC ApplicationProfiles
type ApplicationProfiles struct {
	Metadata Metadata               `json:"metadata"`
	Spec     map[string]interface{} `json:"spec"`
}

// CreateApplicationProfiles creates a new ApplicationProfiles
func (c *Client) CreateApplicationProfiles(ctx context.Context, resource *ApplicationProfiles) (*ApplicationProfiles, error) {
	var result ApplicationProfiles
	path := fmt.Sprintf("/api/config/namespaces/%s/application_profiless", resource.Metadata.Namespace)
	err := c.Post(ctx, path, resource, &result)
	return &result, err
}

// GetApplicationProfiles retrieves a ApplicationProfiles
func (c *Client) GetApplicationProfiles(ctx context.Context, namespace, name string) (*ApplicationProfiles, error) {
	var result ApplicationProfiles
	path := fmt.Sprintf("/api/config/namespaces/%s/application_profiless/%s", namespace, name)
	err := c.Get(ctx, path, &result)
	return &result, err
}

// UpdateApplicationProfiles updates a ApplicationProfiles
func (c *Client) UpdateApplicationProfiles(ctx context.Context, resource *ApplicationProfiles) (*ApplicationProfiles, error) {
	var result ApplicationProfiles
	path := fmt.Sprintf("/api/config/namespaces/%s/application_profiless/%s", resource.Metadata.Namespace, resource.Metadata.Name)
	err := c.Put(ctx, path, resource, &result)
	return &result, err
}

// DeleteApplicationProfiles deletes a ApplicationProfiles
func (c *Client) DeleteApplicationProfiles(ctx context.Context, namespace, name string) error {
	path := fmt.Sprintf("/api/config/namespaces/%s/application_profiless/%s", namespace, name)
	return c.Delete(ctx, path)
}
