// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package client

import (
	"context"
	"fmt"
)

// AuthorizationServer represents a XCSH AuthorizationServer
type AuthorizationServer struct {
	Metadata Metadata               `json:"metadata"`
	Spec     map[string]interface{} `json:"spec"`
}

// CreateAuthorizationServer creates a new AuthorizationServer
func (c *Client) CreateAuthorizationServer(ctx context.Context, resource *AuthorizationServer) (*AuthorizationServer, error) {
	var result AuthorizationServer
	path := fmt.Sprintf("/api/config/namespaces/%s/authorization_servers", resource.Metadata.Namespace)
	err := c.Post(ctx, path, resource, &result)
	return &result, err
}

// GetAuthorizationServer retrieves a AuthorizationServer
func (c *Client) GetAuthorizationServer(ctx context.Context, namespace, name string) (*AuthorizationServer, error) {
	var result AuthorizationServer
	path := fmt.Sprintf("/api/config/namespaces/%s/authorization_servers/%s", namespace, name)
	err := c.Get(ctx, path, &result)
	return &result, err
}

// UpdateAuthorizationServer updates a AuthorizationServer
func (c *Client) UpdateAuthorizationServer(ctx context.Context, resource *AuthorizationServer) (*AuthorizationServer, error) {
	var result AuthorizationServer
	path := fmt.Sprintf("/api/config/namespaces/%s/authorization_servers/%s", resource.Metadata.Namespace, resource.Metadata.Name)
	err := c.Put(ctx, path, resource, &result)
	return &result, err
}

// DeleteAuthorizationServer deletes a AuthorizationServer
func (c *Client) DeleteAuthorizationServer(ctx context.Context, namespace, name string) error {
	path := fmt.Sprintf("/api/config/namespaces/%s/authorization_servers/%s", namespace, name)
	return c.Delete(ctx, path)
}
