// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package client

import (
	"context"
	"fmt"
)

// BigIPHTTPProxy represents a XCSH BigIPHTTPProxy
type BigIPHTTPProxy struct {
	Metadata Metadata               `json:"metadata"`
	Spec     map[string]interface{} `json:"spec"`
}

// CreateBigIPHTTPProxy creates a new BigIPHTTPProxy
func (c *Client) CreateBigIPHTTPProxy(ctx context.Context, resource *BigIPHTTPProxy) (*BigIPHTTPProxy, error) {
	var result BigIPHTTPProxy
	path := fmt.Sprintf("/api/config/namespaces/%s/bigip_http_proxys", resource.Metadata.Namespace)
	err := c.Post(ctx, path, resource, &result)
	return &result, err
}

// GetBigIPHTTPProxy retrieves a BigIPHTTPProxy
func (c *Client) GetBigIPHTTPProxy(ctx context.Context, namespace, name string) (*BigIPHTTPProxy, error) {
	var result BigIPHTTPProxy
	path := fmt.Sprintf("/api/config/namespaces/%s/bigip_http_proxys/%s", namespace, name)
	err := c.Get(ctx, path, &result)
	return &result, err
}

// UpdateBigIPHTTPProxy updates a BigIPHTTPProxy
func (c *Client) UpdateBigIPHTTPProxy(ctx context.Context, resource *BigIPHTTPProxy) (*BigIPHTTPProxy, error) {
	var result BigIPHTTPProxy
	path := fmt.Sprintf("/api/config/namespaces/%s/bigip_http_proxys/%s", resource.Metadata.Namespace, resource.Metadata.Name)
	err := c.Put(ctx, path, resource, &result)
	return &result, err
}

// DeleteBigIPHTTPProxy deletes a BigIPHTTPProxy
func (c *Client) DeleteBigIPHTTPProxy(ctx context.Context, namespace, name string) error {
	path := fmt.Sprintf("/api/config/namespaces/%s/bigip_http_proxys/%s", namespace, name)
	return c.Delete(ctx, path)
}
