// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification — read-only client (GET only)

package client

import (
	"context"
	"fmt"
)

// BigIPVirtualServer represents a read-only F5 XC BigIPVirtualServer
type BigIPVirtualServer struct {
	Metadata Metadata               `json:"metadata"`
	Spec     map[string]interface{} `json:"spec"`
}

// GetBigIPVirtualServer retrieves a BigIPVirtualServer (read-only)
func (c *Client) GetBigIPVirtualServer(ctx context.Context, namespace, name string) (*BigIPVirtualServer, error) {
	var result BigIPVirtualServer
	path := fmt.Sprintf("/api/config/namespaces/%s/bigip_virtual_servers/%s", namespace, name)
	err := c.Get(ctx, path, &result)
	return &result, err
}
