// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package client

import (
	"context"
	"fmt"
)

// CDNPurgeCommand represents a XCSH CDNPurgeCommand
type CDNPurgeCommand struct {
	Metadata Metadata               `json:"metadata"`
	Spec     map[string]interface{} `json:"spec"`
}

// CreateCDNPurgeCommand creates a new CDNPurgeCommand
func (c *Client) CreateCDNPurgeCommand(ctx context.Context, resource *CDNPurgeCommand) (*CDNPurgeCommand, error) {
	var result CDNPurgeCommand
	path := fmt.Sprintf("/api/config/namespaces/%s/cdn_purge_commands", resource.Metadata.Namespace)
	err := c.Post(ctx, path, resource, &result)
	return &result, err
}

// GetCDNPurgeCommand retrieves a CDNPurgeCommand
func (c *Client) GetCDNPurgeCommand(ctx context.Context, namespace, name string) (*CDNPurgeCommand, error) {
	var result CDNPurgeCommand
	path := fmt.Sprintf("/api/config/namespaces/%s/cdn_purge_commands/%s", namespace, name)
	err := c.Get(ctx, path, &result)
	return &result, err
}

// UpdateCDNPurgeCommand updates a CDNPurgeCommand
func (c *Client) UpdateCDNPurgeCommand(ctx context.Context, resource *CDNPurgeCommand) (*CDNPurgeCommand, error) {
	var result CDNPurgeCommand
	path := fmt.Sprintf("/api/config/namespaces/%s/cdn_purge_commands/%s", resource.Metadata.Namespace, resource.Metadata.Name)
	err := c.Put(ctx, path, resource, &result)
	return &result, err
}

// DeleteCDNPurgeCommand deletes a CDNPurgeCommand
func (c *Client) DeleteCDNPurgeCommand(ctx context.Context, namespace, name string) error {
	path := fmt.Sprintf("/api/config/namespaces/%s/cdn_purge_commands/%s", namespace, name)
	return c.Delete(ctx, path)
}
