// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification — read-only client (GET only)

package client

import (
	"context"
	"fmt"
)

// CertifiedHardware represents a read-only F5 XC CertifiedHardware
type CertifiedHardware struct {
	Metadata Metadata               `json:"metadata"`
	Spec     map[string]interface{} `json:"spec"`
}

// GetCertifiedHardware retrieves a CertifiedHardware (read-only)
func (c *Client) GetCertifiedHardware(ctx context.Context, namespace, name string) (*CertifiedHardware, error) {
	var result CertifiedHardware
	path := fmt.Sprintf("/api/config/namespaces/%s/certified_hardwares/%s", namespace, name)
	err := c.Get(ctx, path, &result)
	return &result, err
}
