// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package client

import (
	"context"
	"fmt"
)

// DNSProxy represents a XCSH DNSProxy
type DNSProxy struct {
	Metadata Metadata               `json:"metadata"`
	Spec     map[string]interface{} `json:"spec"`
}

// CreateDNSProxy creates a new DNSProxy
func (c *Client) CreateDNSProxy(ctx context.Context, resource *DNSProxy) (*DNSProxy, error) {
	var result DNSProxy
	path := fmt.Sprintf("/api/config/namespaces/%s/dns_proxys", resource.Metadata.Namespace)
	err := c.Post(ctx, path, resource, &result)
	return &result, err
}

// GetDNSProxy retrieves a DNSProxy
func (c *Client) GetDNSProxy(ctx context.Context, namespace, name string) (*DNSProxy, error) {
	var result DNSProxy
	path := fmt.Sprintf("/api/config/namespaces/%s/dns_proxys/%s", namespace, name)
	err := c.Get(ctx, path, &result)
	return &result, err
}

// UpdateDNSProxy updates a DNSProxy
func (c *Client) UpdateDNSProxy(ctx context.Context, resource *DNSProxy) (*DNSProxy, error) {
	var result DNSProxy
	path := fmt.Sprintf("/api/config/namespaces/%s/dns_proxys/%s", resource.Metadata.Namespace, resource.Metadata.Name)
	err := c.Put(ctx, path, resource, &result)
	return &result, err
}

// DeleteDNSProxy deletes a DNSProxy
func (c *Client) DeleteDNSProxy(ctx context.Context, namespace, name string) error {
	path := fmt.Sprintf("/api/config/namespaces/%s/dns_proxys/%s", namespace, name)
	return c.Delete(ctx, path)
}
