// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification — read-only client (GET only)

package client

import (
	"context"
	"fmt"
)

// FlowAnomaly represents a read-only F5 XC FlowAnomaly
type FlowAnomaly struct {
	Metadata Metadata               `json:"metadata"`
	Spec     map[string]interface{} `json:"spec"`
}

// GetFlowAnomaly retrieves a FlowAnomaly (read-only)
func (c *Client) GetFlowAnomaly(ctx context.Context, namespace, name string) (*FlowAnomaly, error) {
	var result FlowAnomaly
	path := fmt.Sprintf("/api/config/namespaces/%s/flow_anomalys/%s", namespace, name)
	err := c.Get(ctx, path, &result)
	return &result, err
}
