// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification — read-only client (GET only)

package client

import (
	"context"
	"fmt"
)

// LmaRegion represents a read-only F5 XC LmaRegion
type LmaRegion struct {
	Metadata Metadata               `json:"metadata"`
	Spec     map[string]interface{} `json:"spec"`
}

// GetLmaRegion retrieves a LmaRegion (read-only)
func (c *Client) GetLmaRegion(ctx context.Context, namespace, name string) (*LmaRegion, error) {
	var result LmaRegion
	path := fmt.Sprintf("/api/config/namespaces/%s/lma_regions/%s", namespace, name)
	err := c.Get(ctx, path, &result)
	return &result, err
}
