// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification — read-only client (GET only)

package client

import (
	"context"
	"fmt"
)

// NetworkPolicySet represents a read-only F5 XC NetworkPolicySet
type NetworkPolicySet struct {
	Metadata Metadata               `json:"metadata"`
	Spec     map[string]interface{} `json:"spec"`
}

// GetNetworkPolicySet retrieves a NetworkPolicySet (read-only)
func (c *Client) GetNetworkPolicySet(ctx context.Context, namespace, name string) (*NetworkPolicySet, error) {
	var result NetworkPolicySet
	path := fmt.Sprintf("/api/config/namespaces/%s/network_policy_sets/%s", namespace, name)
	err := c.Get(ctx, path, &result)
	return &result, err
}
