// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification — read-only client (GET only)

package client

import (
	"context"
	"fmt"
)

// NginxCsg represents a read-only F5 XC NginxCsg
type NginxCsg struct {
	Metadata Metadata               `json:"metadata"`
	Spec     map[string]interface{} `json:"spec"`
}

// GetNginxCsg retrieves a NginxCsg (read-only)
func (c *Client) GetNginxCsg(ctx context.Context, namespace, name string) (*NginxCsg, error) {
	var result NginxCsg
	path := fmt.Sprintf("/api/config/namespaces/%s/nginx_csgs/%s", namespace, name)
	err := c.Get(ctx, path, &result)
	return &result, err
}
