// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification — read-only client (GET only)

package client

import (
	"context"
	"fmt"
)

// NginxInstance represents a read-only F5 XC NginxInstance
type NginxInstance struct {
	Metadata Metadata               `json:"metadata"`
	Spec     map[string]interface{} `json:"spec"`
}

// GetNginxInstance retrieves a NginxInstance (read-only)
func (c *Client) GetNginxInstance(ctx context.Context, namespace, name string) (*NginxInstance, error) {
	var result NginxInstance
	path := fmt.Sprintf("/api/config/namespaces/%s/nginx_instances/%s", namespace, name)
	err := c.Get(ctx, path, &result)
	return &result, err
}
