// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification — read-only client (GET only)

package client

import (
	"context"
	"fmt"
)

// NginxServer represents a read-only F5 XC NginxServer
type NginxServer struct {
	Metadata Metadata               `json:"metadata"`
	Spec     map[string]interface{} `json:"spec"`
}

// GetNginxServer retrieves a NginxServer (read-only)
func (c *Client) GetNginxServer(ctx context.Context, namespace, name string) (*NginxServer, error) {
	var result NginxServer
	path := fmt.Sprintf("/api/config/namespaces/%s/nginx_servers/%s", namespace, name)
	err := c.Get(ctx, path, &result)
	return &result, err
}
