// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification — read-only client (GET only)

package client

import (
	"context"
	"fmt"
)

// ServicePolicySet represents a read-only F5 XC ServicePolicySet
type ServicePolicySet struct {
	Metadata Metadata               `json:"metadata"`
	Spec     map[string]interface{} `json:"spec"`
}

// GetServicePolicySet retrieves a ServicePolicySet (read-only)
func (c *Client) GetServicePolicySet(ctx context.Context, namespace, name string) (*ServicePolicySet, error) {
	var result ServicePolicySet
	path := fmt.Sprintf("/api/config/namespaces/%s/service_policy_sets/%s", namespace, name)
	err := c.Get(ctx, path, &result)
	return &result, err
}
