// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification — read-only client (GET only)

package client

import (
	"context"
	"fmt"
)

// ShapeBotDefenseInstance represents a read-only F5 XC ShapeBotDefenseInstance
type ShapeBotDefenseInstance struct {
	Metadata Metadata               `json:"metadata"`
	Spec     map[string]interface{} `json:"spec"`
}

// GetShapeBotDefenseInstance retrieves a ShapeBotDefenseInstance (read-only)
func (c *Client) GetShapeBotDefenseInstance(ctx context.Context, namespace, name string) (*ShapeBotDefenseInstance, error) {
	var result ShapeBotDefenseInstance
	path := fmt.Sprintf("/api/config/namespaces/%s/shape_bot_defense_instances/%s", namespace, name)
	err := c.Get(ctx, path, &result)
	return &result, err
}
