// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification — read-only client (GET only)

package client

import (
	"context"
	"fmt"
)

// ThirdPartyApplication represents a read-only F5 XC ThirdPartyApplication
type ThirdPartyApplication struct {
	Metadata Metadata               `json:"metadata"`
	Spec     map[string]interface{} `json:"spec"`
}

// GetThirdPartyApplication retrieves a ThirdPartyApplication (read-only)
func (c *Client) GetThirdPartyApplication(ctx context.Context, namespace, name string) (*ThirdPartyApplication, error) {
	var result ThirdPartyApplication
	path := fmt.Sprintf("/api/config/namespaces/%s/third_party_applications/%s", namespace, name)
	err := c.Get(ctx, path, &result)
	return &result, err
}
