// Copyright (c) 2026 Robin Mordasiewicz. MIT License.

// Package codegen provides Go text/template constants used by the file
// generation functions in generate.go. Each constant is the template for
// one output file type (resource, client types, data source).
package codegen

const ResourceTemplate = `// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
{{- if .UsesBoolPlanModifier}}
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/boolplanmodifier"
{{- end}}
{{- if .UsesInt64PlanModifier}}
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
{{- end}}
{{- if .UsesListPlanModifier}}
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
{{- end}}
{{- if .UsesMapPlanModifier}}
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/mapplanmodifier"
{{- end}}
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
{{- if .HasBlocks}}
	"github.com/hashicorp/terraform-plugin-framework/attr"
{{- end}}
{{- if or .HasMaxLengthValidators .HasEnumValidators .HasPatternValidators}}
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
{{- end}}
{{- if .HasListSizeValidators}}
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
{{- end}}
{{- if .HasInt64RangeValidators}}
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
{{- end}}
{{- if .HasPatternValidators}}
	"regexp"
{{- end}}
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/f5xc-salesdemos/terraform-provider-f5xc/internal/client"
	inttimeouts "github.com/f5xc-salesdemos/terraform-provider-f5xc/internal/timeouts"
	"github.com/f5xc-salesdemos/terraform-provider-f5xc/internal/validators"
)

// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource                   = &{{.TitleCase}}Resource{}
	_ resource.ResourceWithConfigure      = &{{.TitleCase}}Resource{}
	_ resource.ResourceWithImportState    = &{{.TitleCase}}Resource{}
	_ resource.ResourceWithModifyPlan     = &{{.TitleCase}}Resource{}
	_ resource.ResourceWithValidateConfig = &{{.TitleCase}}Resource{}
)

func New{{.TitleCase}}Resource() resource.Resource {
	return &{{.TitleCase}}Resource{}
}

type {{.TitleCase}}Resource struct {
	client *client.Client
}

{{renderNestedModelTypes .TitleCase .Attributes}}type {{.TitleCase}}ResourceModel struct {
{{- range .Attributes}}
{{- if not .IsBlock}}
	{{.GoName}} types.{{if eq .Type "string"}}String{{else if eq .Type "int64"}}Int64{{else if eq .Type "bool"}}Bool{{else if eq .Type "map"}}Map{{else if eq .Type "list"}}List{{else}}String{{end}} ` + "`" + `tfsdk:"{{.TfsdkTag}}"` + "`" + `
{{- end}}
{{- end}}
	Timeouts timeouts.Value ` + "`" + `tfsdk:"timeouts"` + "`" + `
{{renderBlockFields .TitleCase .Attributes}}}

func (r *{{.TitleCase}}Resource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_{{.Name}}"
}

func (r *{{.TitleCase}}Resource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "{{.Description}}",
		Attributes: map[string]schema.Attribute{
{{- range .Attributes}}
{{- if not .IsBlock}}
			"{{.TfsdkTag}}": schema.{{if eq .Type "string"}}String{{else if eq .Type "int64"}}Int64{{else if eq .Type "bool"}}Bool{{else if eq .Type "map"}}Map{{else if eq .Type "list"}}List{{else}}String{{end}}Attribute{
				MarkdownDescription: "{{.Description}}",
{{- if .DeprecationMessage}}
				DeprecationMessage: "{{.DeprecationMessage}}",
{{- end}}
{{- if .Required}}
				Required: true,
{{- end}}
{{- if and .Optional (not .Required)}}
				Optional: true,
{{- end}}
{{- if .Computed}}
				Computed: true,
{{- end}}
{{- if eq .Type "map"}}
				ElementType: types.StringType,
{{- end}}
{{- if eq .Type "list"}}
				ElementType: {{if eq .ElementType "int64"}}types.Int64Type{{else if eq .ElementType "bool"}}types.BoolType{{else}}types.StringType{{end}},
{{- end}}
{{- if .PlanModifier}}
				PlanModifiers: []planmodifier.{{if eq .Type "string"}}String{{else if eq .Type "bool"}}Bool{{else if eq .Type "int64"}}Int64{{else if eq .Type "list"}}List{{else if eq .Type "map"}}Map{{else}}String{{end}}{
{{- if eq .PlanModifier "RequiresReplace"}}
					{{if eq .Type "string"}}stringplanmodifier{{else if eq .Type "bool"}}boolplanmodifier{{else if eq .Type "int64"}}int64planmodifier{{else if eq .Type "list"}}listplanmodifier{{else if eq .Type "map"}}mapplanmodifier{{else}}stringplanmodifier{{end}}.RequiresReplace(),
{{- else if eq .PlanModifier "UseStateForUnknown"}}
					{{if eq .Type "string"}}stringplanmodifier{{else if eq .Type "bool"}}boolplanmodifier{{else if eq .Type "int64"}}int64planmodifier{{else if eq .Type "list"}}listplanmodifier{{else if eq .Type "map"}}mapplanmodifier{{else}}stringplanmodifier{{end}}.UseStateForUnknown(),
{{- end}}
				},
{{- end}}
{{- if eq .TfsdkTag "name"}}
				Validators: []validator.String{
{{- if .UseDomainValidator}}
					validators.DomainValidator(),
{{- else}}
					validators.NameValidator(),
{{- end}}
				},
{{- else if eq .TfsdkTag "namespace"}}
				Validators: []validator.String{
					validators.NamespaceValidator(),
				},
{{- else if and (eq .Type "string") (or (gt .MinLength 0) (gt .MaxLength 0) (ne .Pattern "") (gt (len .EnumValues) 0))}}
				Validators: []validator.String{
{{- if and (gt .MinLength 0) (gt .MaxLength 0)}}
					stringvalidator.LengthBetween({{.MinLength}}, {{.MaxLength}}),
{{- else if gt .MaxLength 0}}
					stringvalidator.LengthAtMost({{.MaxLength}}),
{{- else if gt .MinLength 0}}
					stringvalidator.LengthAtLeast({{.MinLength}}),
{{- end}}
{{- if ne .Pattern ""}}
					stringvalidator.RegexMatches(regexp.MustCompile({{regexLiteral .Pattern}}), ""),
{{- end}}
{{- if gt (len .EnumValues) 0}}
					stringvalidator.OneOf({{enumValuesLiteral .EnumValues}}),
{{- end}}
				},
{{- else if and (or (eq .Type "list") (eq .Type "set")) (or (gt .MinItems 0) (gt .MaxItems 0))}}
				Validators: []validator.List{
{{- if and (gt .MinItems 0) (gt .MaxItems 0)}}
					listvalidator.SizeBetween({{.MinItems}}, {{.MaxItems}}),
{{- else if gt .MaxItems 0}}
					listvalidator.SizeAtMost({{.MaxItems}}),
{{- else}}
					listvalidator.SizeAtLeast({{.MinItems}}),
{{- end}}
				},
{{- else if and (eq .Type "int64") (or (gt .Minimum 0) (gt .Maximum 0))}}
				Validators: []validator.Int64{
{{- if and (gt .Minimum 0) (gt .Maximum 0)}}
					int64validator.Between({{.Minimum}}, {{.Maximum}}),
{{- else if gt .Maximum 0}}
					int64validator.AtMost({{.Maximum}}),
{{- else}}
					int64validator.AtLeast({{.Minimum}}),
{{- end}}
				},
{{- end}}
			},
{{- end}}
{{- end}}
		},
		Blocks: map[string]schema.Block{
			"timeouts": timeouts.Block(ctx, timeouts.Opts{
				Create: true,
				Read:   true,
				Update: true,
				Delete: true,
			}),
{{- range .Attributes}}
{{- if .IsBlock}}
			"{{.TfsdkTag}}": schema.{{if eq .NestedBlockType "single"}}SingleNestedBlock{{else if eq .NestedBlockType "list"}}ListNestedBlock{{else}}SingleNestedBlock{{end}}{
				MarkdownDescription: "{{.Description}}",
{{- if eq .NestedBlockType "list"}}
				NestedObject: schema.NestedBlockObject{
{{- if .NestedAttributes}}
{{renderNestedAttrs .NestedAttributes "\t\t\t\t\t"}}{{renderNestedBlocks .NestedAttributes "\t\t\t\t\t"}}{{- else}}
					Attributes: map[string]schema.Attribute{},
{{- end}}
				},
{{- else}}
{{- if .NestedAttributes}}
{{renderNestedAttrs .NestedAttributes "\t\t\t\t"}}{{renderNestedBlocks .NestedAttributes "\t\t\t\t"}}{{- end}}
{{- end}}
			},
{{- end}}
{{- end}}
		},
	}
}

func (r *{{.TitleCase}}Resource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.client = client
}

// ValidateConfig implements resource.ResourceWithValidateConfig
func (r *{{.TitleCase}}Resource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var data {{.TitleCase}}ResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
{{- if .HasConflicts}}
{{.ConflictCheckCode}}
{{- end}}
}

// ModifyPlan implements resource.ResourceWithModifyPlan
func (r *{{.TitleCase}}Resource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() {
		resp.Diagnostics.AddWarning(
			"Resource Destruction",
			"This will permanently delete the {{.Name}} from F5 Distributed Cloud.",
		)
		return
	}

	if req.State.Raw.IsNull() {
		var plan {{.TitleCase}}ResourceModel
		resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
		if resp.Diagnostics.HasError() {
			return
		}

		if plan.Name.IsUnknown() {
			resp.Diagnostics.AddWarning(
				"Unknown Resource Name",
				"The resource name is not yet known. This may affect planning for dependent resources.",
			)
		}
	}
}

func (r *{{.TitleCase}}Resource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data {{.TitleCase}}ResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createTimeout, diags := data.Timeouts.Create(ctx, inttimeouts.DefaultCreate)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, createTimeout)
	defer cancel()

	tflog.Debug(ctx, "Creating {{.Name}}", map[string]interface{}{
		"name":      data.Name.ValueString(),
		"namespace": data.Namespace.ValueString(),
	})

	createReq := &client.{{.TitleCase}}{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: make(map[string]interface{}),
	}

	if !data.Description.IsNull() {
		createReq.Metadata.Description = data.Description.ValueString()
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.Metadata.Labels = labels
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.Metadata.Annotations = annotations
	}

	// Marshal spec fields from Terraform state to API struct
{{renderSpecMarshalCodeForCreate .Attributes "\t" .TitleCase}}

	apiResource, err := r.client.Create{{.TitleCase}}(ctx, createReq)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create {{.TitleCase}}: %s", err))
		return
	}

	data.ID = types.StringValue(apiResource.Metadata.Name)
{{- if not .HasNamespaceInPath}}
	// For resources without namespace in API path, namespace is computed from API response
	data.Namespace = types.StringValue(apiResource.Metadata.Namespace)
{{- end}}

	// Unmarshal spec fields from API response to Terraform state
	// This ensures computed nested fields (like tenant in Object Reference blocks) have known values
	isImport := false // Create is never an import
	_ = isImport // May be unused if resource has no blocks needing import detection
{{renderSpecUnmarshalCode .Attributes "\t" .TitleCase}}

	tflog.Trace(ctx, "created {{.TitleCase}} resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *{{.TitleCase}}Resource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data {{.TitleCase}}ResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	readTimeout, diags := data.Timeouts.Read(ctx, inttimeouts.DefaultRead)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, readTimeout)
	defer cancel()

	apiResource, err := r.client.Get{{.TitleCase}}(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		// Check if the resource was deleted outside Terraform
		if strings.Contains(err.Error(), "NOT_FOUND") || strings.Contains(err.Error(), "404") {
			tflog.Warn(ctx, "{{.TitleCase}} not found, removing from state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read {{.TitleCase}}: %s", err))
		return
	}

	data.ID = types.StringValue(apiResource.Metadata.Name)
	data.Name = types.StringValue(apiResource.Metadata.Name)
	data.Namespace = types.StringValue(apiResource.Metadata.Namespace)

	// Read description from metadata
	if apiResource.Metadata.Description != "" {
		data.Description = types.StringValue(apiResource.Metadata.Description)
	} else {
		data.Description = types.StringNull()
	}

	// Filter out system-managed labels (ves.io/*) that are injected by the platform
	if len(apiResource.Metadata.Labels) > 0 {
		filteredLabels := filterSystemLabels(apiResource.Metadata.Labels)
		if len(filteredLabels) > 0 {
			labels, diags := types.MapValueFrom(ctx, types.StringType, filteredLabels)
			resp.Diagnostics.Append(diags...)
			if !resp.Diagnostics.HasError() {
				data.Labels = labels
			}
		} else {
			data.Labels = types.MapNull(types.StringType)
		}
	} else {
		data.Labels = types.MapNull(types.StringType)
	}

	if len(apiResource.Metadata.Annotations) > 0 {
		annotations, diags := types.MapValueFrom(ctx, types.StringType, apiResource.Metadata.Annotations)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Annotations = annotations
		}
	} else {
		data.Annotations = types.MapNull(types.StringType)
	}

	// Check if this Read is triggered by an import operation
	// Import sets a private state marker so we know to populate all nested blocks from API response
	isImport := false
	if importMarker, diags := req.Private.GetKey(ctx, "isImport"); diags.HasError() == false && string(importMarker) == "true" {
		isImport = true
	}
	_ = isImport // May be unused if resource has no blocks needing import detection
{{renderSpecUnmarshalCode .Attributes "\t" .TitleCase}}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *{{.TitleCase}}Resource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data {{.TitleCase}}ResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	updateTimeout, diags := data.Timeouts.Update(ctx, inttimeouts.DefaultUpdate)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, updateTimeout)
	defer cancel()

	apiResource := &client.{{.TitleCase}}{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: make(map[string]interface{}),
	}

	if !data.Description.IsNull() {
		apiResource.Metadata.Description = data.Description.ValueString()
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Labels = labels
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Annotations = annotations
	}

	// Marshal spec fields from Terraform state to API struct
{{renderSpecMarshalCode .Attributes "\t" .TitleCase}}

	_, err := r.client.Update{{.TitleCase}}(ctx, apiResource)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update {{.TitleCase}}: %s", err))
		return
	}

	// Use plan data for ID since API response may not include metadata.name
	data.ID = types.StringValue(data.Name.ValueString())

	// Fetch the resource to get complete state including computed fields
	// PUT responses may not include all computed nested fields (like tenant in Object Reference blocks)
	fetched, fetchErr := r.client.Get{{.TitleCase}}(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if fetchErr != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read {{.TitleCase}} after update: %s", fetchErr))
		return
	}

{{renderFetchedComputedFieldsCode .Attributes "\t"}}

	// Unmarshal spec fields from fetched resource to Terraform state
	apiResource = fetched // Use GET response which includes all computed fields
	isImport := false // Update is never an import
	_ = isImport // May be unused if resource has no blocks needing import detection
{{renderSpecUnmarshalCode .Attributes "\t" .TitleCase}}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *{{.TitleCase}}Resource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data {{.TitleCase}}ResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	deleteTimeout, diags := data.Timeouts.Delete(ctx, inttimeouts.DefaultDelete)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, deleteTimeout)
	defer cancel()

{{- if eq .TitleCase "Namespace"}}
	// Namespace requires cascade_delete endpoint (standard DELETE returns 501)
	err := r.client.CascadeDeleteNamespace(ctx, data.Name.ValueString())
{{- else}}
	err := r.client.Delete{{.TitleCase}}(ctx, data.Namespace.ValueString(), data.Name.ValueString())
{{- end}}
	if err != nil {
		// If the resource is already gone, consider deletion successful (idempotent delete)
		if strings.Contains(err.Error(), "NOT_FOUND") || strings.Contains(err.Error(), "404") {
			tflog.Warn(ctx, "{{.TitleCase}} already deleted, removing from state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			return
		}
		// If delete is not implemented (501), warn and remove from state
		// Some F5 XC resources don't support deletion via API
		if strings.Contains(err.Error(), "501") {
			tflog.Warn(ctx, "{{.TitleCase}} delete not supported by API (501), removing from state only", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete {{.TitleCase}}: %s", err))
		return
	}
}

func (r *{{.TitleCase}}Resource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
{{- if .HasNamespaceInPath}}
	// Import ID format: namespace/name
	parts := strings.Split(req.ID, "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError(
			"Invalid Import ID",
			fmt.Sprintf("Expected import ID format: namespace/name, got: %s", req.ID),
		)
		return
	}
	namespace := parts[0]
	name := parts[1]

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("namespace"), namespace)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), name)...)
{{- else}}
	// Import ID format: name (no namespace for this resource type)
	name := req.ID
	if name == "" {
		resp.Diagnostics.AddError(
			"Invalid Import ID",
			"Expected import ID to be the resource name, got empty string",
		)
		return
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("namespace"), "")...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), name)...)
{{- end}}

	// Set private state marker to indicate this is an import operation
	// This allows Read to populate all nested blocks from API response
	diags := resp.Private.SetKey(ctx, "isImport", []byte("true"))
	resp.Diagnostics.Append(diags...)
}
`

const ClientTemplate = `// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package client

import (
	"context"
	"fmt"
)

// {{.TitleCase}} represents a F5XC {{.TitleCase}}
type {{.TitleCase}} struct {
	Metadata Metadata               ` + "`" + `json:"metadata"` + "`" + `
	Spec     map[string]interface{} ` + "`" + `json:"spec"` + "`" + `
}

// Create{{.TitleCase}} creates a new {{.TitleCase}}
func (c *Client) Create{{.TitleCase}}(ctx context.Context, resource *{{.TitleCase}}) (*{{.TitleCase}}, error) {
	var result {{.TitleCase}}
{{- if .HasNamespaceInPath}}
	path := fmt.Sprintf("{{.APIPath}}", resource.Metadata.Namespace)
{{- else}}
	path := "{{.APIPath}}"
	_ = resource.Metadata.Namespace // Namespace not required in API path for this resource
{{- end}}
	err := c.Post(ctx, path, resource, &result)
	return &result, err
}

// Get{{.TitleCase}} retrieves a {{.TitleCase}}
func (c *Client) Get{{.TitleCase}}(ctx context.Context, namespace, name string) (*{{.TitleCase}}, error) {
	var result {{.TitleCase}}
{{- if .HasNamespaceInPath}}
	path := fmt.Sprintf("{{.APIPathItem}}", namespace, name)
{{- else}}
	path := fmt.Sprintf("{{.APIPathItem}}", name)
	_ = namespace // Namespace not required in API path for this resource
{{- end}}
	err := c.Get(ctx, path, &result)
	return &result, err
}

// Update{{.TitleCase}} updates a {{.TitleCase}}
func (c *Client) Update{{.TitleCase}}(ctx context.Context, resource *{{.TitleCase}}) (*{{.TitleCase}}, error) {
	var result {{.TitleCase}}
{{- if .HasNamespaceInPath}}
	path := fmt.Sprintf("{{.APIPathItem}}", resource.Metadata.Namespace, resource.Metadata.Name)
{{- else}}
	path := fmt.Sprintf("{{.APIPathItem}}", resource.Metadata.Name)
	_ = resource.Metadata.Namespace // Namespace not required in API path for this resource
{{- end}}
	err := c.Put(ctx, path, resource, &result)
	return &result, err
}

// Delete{{.TitleCase}} deletes a {{.TitleCase}}
func (c *Client) Delete{{.TitleCase}}(ctx context.Context, namespace, name string) error {
{{- if .HasNamespaceInPath}}
	path := fmt.Sprintf("{{.APIPathItem}}", namespace, name)
{{- else}}
	path := fmt.Sprintf("{{.APIPathItem}}", name)
	_ = namespace // Namespace not required in API path for this resource
{{- end}}
	return c.Delete(ctx, path)
}
`

const DataSourceTemplate = `// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/f5xc-salesdemos/terraform-provider-f5xc/internal/client"
)

var (
	_ datasource.DataSource              = &{{.TitleCase}}DataSource{}
	_ datasource.DataSourceWithConfigure = &{{.TitleCase}}DataSource{}
)

func New{{.TitleCase}}DataSource() datasource.DataSource {
	return &{{.TitleCase}}DataSource{}
}

type {{.TitleCase}}DataSource struct {
	client *client.Client
}

type {{.TitleCase}}DataSourceModel struct {
	ID          types.String ` + "`" + `tfsdk:"id"` + "`" + `
	Name        types.String ` + "`" + `tfsdk:"name"` + "`" + `
	Namespace   types.String ` + "`" + `tfsdk:"namespace"` + "`" + `
	Description types.String ` + "`" + `tfsdk:"description"` + "`" + `
	Labels      types.Map    ` + "`" + `tfsdk:"labels"` + "`" + `
	Annotations types.Map    ` + "`" + `tfsdk:"annotations"` + "`" + `
}

func (d *{{.TitleCase}}DataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_{{.Name}}"
}

func (d *{{.TitleCase}}DataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "{{.Description}}",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier for the resource.",
				Computed:            true,
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "Name of the {{.TitleCase}}.",
				Required:            true,
			},
			"namespace": schema.StringAttribute{
				MarkdownDescription: "Namespace where the {{.TitleCase}} exists.",
				Required:            true,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Description of the {{.TitleCase}}.",
				Computed:            true,
			},
			"labels": schema.MapAttribute{
				MarkdownDescription: "Labels applied to this resource.",
				Computed:            true,
				ElementType:         types.StringType,
			},
			"annotations": schema.MapAttribute{
				MarkdownDescription: "Annotations applied to this resource.",
				Computed:            true,
				ElementType:         types.StringType,
			},
		},
	}
}

func (d *{{.TitleCase}}DataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Data Source Configure Type", "Expected *client.Client")
		return
	}
	d.client = client
}

func (d *{{.TitleCase}}DataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data {{.TitleCase}}DataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resource, err := d.client.Get{{.TitleCase}}(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read {{.TitleCase}}: %s", err))
		return
	}

	data.ID = types.StringValue(resource.Metadata.Name)
	data.Name = types.StringValue(resource.Metadata.Name)
	data.Namespace = types.StringValue(resource.Metadata.Namespace)
	if resource.Metadata.Description != "" {
		data.Description = types.StringValue(resource.Metadata.Description)
	} else {
		data.Description = types.StringNull()
	}

	// Filter out system-managed labels (ves.io/*) that are injected by the platform
	if len(resource.Metadata.Labels) > 0 {
		filteredLabels := filterSystemLabels(resource.Metadata.Labels)
		if len(filteredLabels) > 0 {
			labels, diags := types.MapValueFrom(ctx, types.StringType, filteredLabels)
			resp.Diagnostics.Append(diags...)
			if !resp.Diagnostics.HasError() {
				data.Labels = labels
			}
		} else {
			data.Labels = types.MapNull(types.StringType)
		}
	} else {
		data.Labels = types.MapNull(types.StringType)
	}

	if len(resource.Metadata.Annotations) > 0 {
		annotations, diags := types.MapValueFrom(ctx, types.StringType, resource.Metadata.Annotations)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Annotations = annotations
		}
	} else {
		data.Annotations = types.MapNull(types.StringType)
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
`
