// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/f5xc-salesdemos/terraform-provider-xcsh/internal/client"
	inttimeouts "github.com/f5xc-salesdemos/terraform-provider-xcsh/internal/timeouts"
	"github.com/f5xc-salesdemos/terraform-provider-xcsh/internal/validators"
)

// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource                   = &CDNPurgeCommandResource{}
	_ resource.ResourceWithConfigure      = &CDNPurgeCommandResource{}
	_ resource.ResourceWithImportState    = &CDNPurgeCommandResource{}
	_ resource.ResourceWithModifyPlan     = &CDNPurgeCommandResource{}
	_ resource.ResourceWithValidateConfig = &CDNPurgeCommandResource{}
)

func NewCDNPurgeCommandResource() resource.Resource {
	return &CDNPurgeCommandResource{}
}

type CDNPurgeCommandResource struct {
	client *client.Client
}

// CDNPurgeCommandEmptyModel represents empty nested blocks
type CDNPurgeCommandEmptyModel struct {
}

// CDNPurgeCommandVirtualHostModel represents virtual_host block
type CDNPurgeCommandVirtualHostModel struct {
	Name      types.String `tfsdk:"name"`
	Namespace types.String `tfsdk:"namespace"`
	Tenant    types.String `tfsdk:"tenant"`
}

// CDNPurgeCommandVirtualHostModelAttrTypes defines the attribute types for CDNPurgeCommandVirtualHostModel
var CDNPurgeCommandVirtualHostModelAttrTypes = map[string]attr.Type{
	"name":      types.StringType,
	"namespace": types.StringType,
	"tenant":    types.StringType,
}

type CDNPurgeCommandResourceModel struct {
	Name        types.String                     `tfsdk:"name"`
	Namespace   types.String                     `tfsdk:"namespace"`
	Annotations types.Map                        `tfsdk:"annotations"`
	Description types.String                     `tfsdk:"description"`
	Disable     types.Bool                       `tfsdk:"disable"`
	Labels      types.Map                        `tfsdk:"labels"`
	ID          types.String                     `tfsdk:"id"`
	Hostname    types.String                     `tfsdk:"hostname"`
	Pattern     types.String                     `tfsdk:"pattern"`
	URLPath     types.String                     `tfsdk:"url_path"`
	Timeouts    timeouts.Value                   `tfsdk:"timeouts"`
	HardPurge   *CDNPurgeCommandEmptyModel       `tfsdk:"hard_purge"`
	PurgeAll    *CDNPurgeCommandEmptyModel       `tfsdk:"purge_all"`
	SoftPurge   *CDNPurgeCommandEmptyModel       `tfsdk:"soft_purge"`
	VirtualHost *CDNPurgeCommandVirtualHostModel `tfsdk:"virtual_host"`
}

func (r *CDNPurgeCommandResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_cdn_purge_command"
}

func (r *CDNPurgeCommandResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a CDN Purge Command resource in F5 Distributed Cloud for cdn purge command specification. configuration.",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				MarkdownDescription: "Name of the CDN Purge Command. Must be unique within the namespace.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.NameValidator(),
				},
			},
			"namespace": schema.StringAttribute{
				MarkdownDescription: "Namespace where the CDN Purge Command will be created.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.NamespaceValidator(),
				},
			},
			"annotations": schema.MapAttribute{
				MarkdownDescription: "Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Human readable description for the object.",
				Optional:            true,
			},
			"disable": schema.BoolAttribute{
				MarkdownDescription: "A value of true will administratively disable the object.",
				Optional:            true,
			},
			"labels": schema.MapAttribute{
				MarkdownDescription: "Labels is a user defined key value map that can be attached to resources for organization and filtering.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier for the resource.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"hostname": schema.StringAttribute{
				MarkdownDescription: "[OneOf: hostname, pattern, purge_all, url_path] Exclusive with [pattern purge_all url_path] Purge cached content by Hostname.",
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 1024),
				},
			},
			"pattern": schema.StringAttribute{
				MarkdownDescription: "Exclusive with [hostname purge_all url_path] Purge cached content using PCRE 1 compliant regular expression.",
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 256),
				},
			},
			"url_path": schema.StringAttribute{
				MarkdownDescription: "Exclusive with [hostname pattern purge_all] Purge cache by using a URL path.",
				Optional:            true,
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
		Blocks: map[string]schema.Block{
			"timeouts": timeouts.Block(ctx, timeouts.Opts{
				Create: true,
				Read:   true,
				Update: true,
				Delete: true,
			}),
			"hard_purge": schema.SingleNestedBlock{
				MarkdownDescription: "[OneOf: hard_purge, soft_purge] Enable this option",
			},
			"purge_all": schema.SingleNestedBlock{
				MarkdownDescription: "Enable this option",
			},
			"soft_purge": schema.SingleNestedBlock{
				MarkdownDescription: "Enable this option",
			},
			"virtual_host": schema.SingleNestedBlock{
				MarkdownDescription: "Type establishes a direct reference from one object(the referrer) to another(the referred). Such a reference is in form of tenant/namespace/name.",
				Attributes: map[string]schema.Attribute{
					"name": schema.StringAttribute{
						MarkdownDescription: "When a configuration object(e.g. Virtual_host) refers to another(e.g route) then name will hold the referred object's(e.g. Route's) name.",
						Optional:            true,
						Validators: []validator.String{
							stringvalidator.LengthBetween(1, 128),
						},
					},
					"namespace": schema.StringAttribute{
						MarkdownDescription: "When a configuration object(e.g. Virtual_host) refers to another(e.g route) then namespace will hold the referred object's(e.g. Route's) namespace.",
						Optional:            true,
						Computed:            true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
						Validators: []validator.String{
							stringvalidator.LengthBetween(1, 64),
						},
					},
					"tenant": schema.StringAttribute{
						MarkdownDescription: "When a configuration object(e.g. Virtual_host) refers to another(e.g route) then tenant will hold the referred object's(e.g. Route's) tenant.",
						Optional:            true,
						Computed:            true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
						Validators: []validator.String{
							stringvalidator.LengthAtMost(64),
						},
					},
				},
			},
		},
	}
}

func (r *CDNPurgeCommandResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.client = client
}

// ValidateConfig implements resource.ResourceWithValidateConfig
func (r *CDNPurgeCommandResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var data CDNPurgeCommandResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if !data.Hostname.IsNull() && !data.Pattern.IsNull() {
		resp.Diagnostics.AddAttributeError(
			path.Root("hostname"),
			"Conflicting Configuration",
			"hostname and pattern are mutually exclusive.",
		)
	}
	if !data.Hostname.IsNull() && !data.URLPath.IsNull() {
		resp.Diagnostics.AddAttributeError(
			path.Root("hostname"),
			"Conflicting Configuration",
			"hostname and url_path are mutually exclusive.",
		)
	}
	if !data.Pattern.IsNull() && !data.URLPath.IsNull() {
		resp.Diagnostics.AddAttributeError(
			path.Root("pattern"),
			"Conflicting Configuration",
			"pattern and url_path are mutually exclusive.",
		)
	}

}

// ModifyPlan implements resource.ResourceWithModifyPlan
func (r *CDNPurgeCommandResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() {
		resp.Diagnostics.AddWarning(
			"Resource Destruction",
			"This will permanently delete the cdn_purge_command from F5 Distributed Cloud.",
		)
		return
	}

	if req.State.Raw.IsNull() {
		var plan CDNPurgeCommandResourceModel
		resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
		if resp.Diagnostics.HasError() {
			return
		}

		if plan.Name.IsUnknown() {
			resp.Diagnostics.AddWarning(
				"Unknown Resource Name",
				"The resource name is not yet known. This may affect planning for dependent resources.",
			)
		}
	}
}

func (r *CDNPurgeCommandResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data CDNPurgeCommandResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createTimeout, diags := data.Timeouts.Create(ctx, inttimeouts.DefaultCreate)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, createTimeout)
	defer cancel()

	tflog.Debug(ctx, "Creating cdn_purge_command", map[string]interface{}{
		"name":      data.Name.ValueString(),
		"namespace": data.Namespace.ValueString(),
	})

	createReq := &client.CDNPurgeCommand{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: make(map[string]interface{}),
	}

	if !data.Description.IsNull() {
		createReq.Metadata.Description = data.Description.ValueString()
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.Metadata.Labels = labels
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.Metadata.Annotations = annotations
	}

	// Marshal spec fields from Terraform state to API struct
	if data.HardPurge != nil {
		hard_purgeMap := make(map[string]interface{})
		createReq.Spec["hard_purge"] = hard_purgeMap
	}
	if data.PurgeAll != nil {
		purge_allMap := make(map[string]interface{})
		createReq.Spec["purge_all"] = purge_allMap
	}
	if data.SoftPurge != nil {
		soft_purgeMap := make(map[string]interface{})
		createReq.Spec["soft_purge"] = soft_purgeMap
	}
	if data.VirtualHost != nil {
		virtual_hostMap := make(map[string]interface{})
		if !data.VirtualHost.Name.IsNull() && !data.VirtualHost.Name.IsUnknown() {
			virtual_hostMap["name"] = data.VirtualHost.Name.ValueString()
		}
		if !data.VirtualHost.Namespace.IsNull() && !data.VirtualHost.Namespace.IsUnknown() {
			virtual_hostMap["namespace"] = data.VirtualHost.Namespace.ValueString()
		}
		if !data.VirtualHost.Tenant.IsNull() && !data.VirtualHost.Tenant.IsUnknown() {
			virtual_hostMap["tenant"] = data.VirtualHost.Tenant.ValueString()
		}
		createReq.Spec["virtual_host"] = virtual_hostMap
	}
	if !data.Hostname.IsNull() && !data.Hostname.IsUnknown() {
		createReq.Spec["hostname"] = data.Hostname.ValueString()
	}
	if !data.Pattern.IsNull() && !data.Pattern.IsUnknown() {
		createReq.Spec["pattern"] = data.Pattern.ValueString()
	}
	if !data.URLPath.IsNull() && !data.URLPath.IsUnknown() {
		createReq.Spec["url_path"] = data.URLPath.ValueString()
	}

	apiResource, err := r.client.CreateCDNPurgeCommand(ctx, createReq)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create CDNPurgeCommand: %s", err))
		return
	}

	data.ID = types.StringValue(apiResource.Metadata.Name)

	// Unmarshal spec fields from API response to Terraform state
	// This ensures computed nested fields (like tenant in Object Reference blocks) have known values
	isImport := false // Create is never an import
	_ = isImport      // May be unused if resource has no blocks needing import detection
	if _, ok := apiResource.Spec["hard_purge"].(map[string]interface{}); ok && isImport && data.HardPurge == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.HardPurge = &CDNPurgeCommandEmptyModel{}
	}
	// Normal Read: preserve existing state value
	if _, ok := apiResource.Spec["purge_all"].(map[string]interface{}); ok && isImport && data.PurgeAll == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.PurgeAll = &CDNPurgeCommandEmptyModel{}
	}
	// Normal Read: preserve existing state value
	if _, ok := apiResource.Spec["soft_purge"].(map[string]interface{}); ok && isImport && data.SoftPurge == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.SoftPurge = &CDNPurgeCommandEmptyModel{}
	}
	// Normal Read: preserve existing state value
	if blockData, ok := apiResource.Spec["virtual_host"].(map[string]interface{}); ok && (isImport || data.VirtualHost != nil) {
		data.VirtualHost = &CDNPurgeCommandVirtualHostModel{
			Name: func() types.String {
				if v, ok := blockData["name"].(string); ok && v != "" {
					return types.StringValue(v)
				}
				return types.StringNull()
			}(),
			Namespace: func() types.String {
				if v, ok := blockData["namespace"].(string); ok && v != "" {
					return types.StringValue(v)
				}
				return types.StringNull()
			}(),
			Tenant: func() types.String {
				if v, ok := blockData["tenant"].(string); ok && v != "" {
					return types.StringValue(v)
				}
				return types.StringNull()
			}(),
		}
	}
	if v, ok := apiResource.Spec["hostname"].(string); ok && v != "" {
		data.Hostname = types.StringValue(v)
	} else {
		data.Hostname = types.StringNull()
	}
	if v, ok := apiResource.Spec["pattern"].(string); ok && v != "" {
		data.Pattern = types.StringValue(v)
	} else {
		data.Pattern = types.StringNull()
	}
	if v, ok := apiResource.Spec["url_path"].(string); ok && v != "" {
		data.URLPath = types.StringValue(v)
	} else {
		data.URLPath = types.StringNull()
	}

	tflog.Trace(ctx, "created CDNPurgeCommand resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *CDNPurgeCommandResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data CDNPurgeCommandResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	readTimeout, diags := data.Timeouts.Read(ctx, inttimeouts.DefaultRead)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, readTimeout)
	defer cancel()

	apiResource, err := r.client.GetCDNPurgeCommand(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		// Check if the resource was deleted outside Terraform
		if strings.Contains(err.Error(), "NOT_FOUND") || strings.Contains(err.Error(), "404") {
			tflog.Warn(ctx, "CDNPurgeCommand not found, removing from state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read CDNPurgeCommand: %s", err))
		return
	}

	data.ID = types.StringValue(apiResource.Metadata.Name)
	data.Name = types.StringValue(apiResource.Metadata.Name)
	data.Namespace = types.StringValue(apiResource.Metadata.Namespace)

	// Read description from metadata
	if apiResource.Metadata.Description != "" {
		data.Description = types.StringValue(apiResource.Metadata.Description)
	} else {
		data.Description = types.StringNull()
	}

	// Filter out system-managed labels (ves.io/*) that are injected by the platform
	if len(apiResource.Metadata.Labels) > 0 {
		filteredLabels := filterSystemLabels(apiResource.Metadata.Labels)
		if len(filteredLabels) > 0 {
			labels, diags := types.MapValueFrom(ctx, types.StringType, filteredLabels)
			resp.Diagnostics.Append(diags...)
			if !resp.Diagnostics.HasError() {
				data.Labels = labels
			}
		} else {
			data.Labels = types.MapNull(types.StringType)
		}
	} else {
		data.Labels = types.MapNull(types.StringType)
	}

	if len(apiResource.Metadata.Annotations) > 0 {
		annotations, diags := types.MapValueFrom(ctx, types.StringType, apiResource.Metadata.Annotations)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Annotations = annotations
		}
	} else {
		data.Annotations = types.MapNull(types.StringType)
	}

	// Check if this Read is triggered by an import operation
	// Import sets a private state marker so we know to populate all nested blocks from API response
	isImport := false
	if importMarker, diags := req.Private.GetKey(ctx, "isImport"); diags.HasError() == false && string(importMarker) == "true" {
		isImport = true
	}
	_ = isImport // May be unused if resource has no blocks needing import detection
	if _, ok := apiResource.Spec["hard_purge"].(map[string]interface{}); ok && isImport && data.HardPurge == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.HardPurge = &CDNPurgeCommandEmptyModel{}
	}
	// Normal Read: preserve existing state value
	if _, ok := apiResource.Spec["purge_all"].(map[string]interface{}); ok && isImport && data.PurgeAll == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.PurgeAll = &CDNPurgeCommandEmptyModel{}
	}
	// Normal Read: preserve existing state value
	if _, ok := apiResource.Spec["soft_purge"].(map[string]interface{}); ok && isImport && data.SoftPurge == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.SoftPurge = &CDNPurgeCommandEmptyModel{}
	}
	// Normal Read: preserve existing state value
	if blockData, ok := apiResource.Spec["virtual_host"].(map[string]interface{}); ok && (isImport || data.VirtualHost != nil) {
		data.VirtualHost = &CDNPurgeCommandVirtualHostModel{
			Name: func() types.String {
				if v, ok := blockData["name"].(string); ok && v != "" {
					return types.StringValue(v)
				}
				return types.StringNull()
			}(),
			Namespace: func() types.String {
				if v, ok := blockData["namespace"].(string); ok && v != "" {
					return types.StringValue(v)
				}
				return types.StringNull()
			}(),
			Tenant: func() types.String {
				if v, ok := blockData["tenant"].(string); ok && v != "" {
					return types.StringValue(v)
				}
				return types.StringNull()
			}(),
		}
	}
	if v, ok := apiResource.Spec["hostname"].(string); ok && v != "" {
		data.Hostname = types.StringValue(v)
	} else {
		data.Hostname = types.StringNull()
	}
	if v, ok := apiResource.Spec["pattern"].(string); ok && v != "" {
		data.Pattern = types.StringValue(v)
	} else {
		data.Pattern = types.StringNull()
	}
	if v, ok := apiResource.Spec["url_path"].(string); ok && v != "" {
		data.URLPath = types.StringValue(v)
	} else {
		data.URLPath = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *CDNPurgeCommandResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data CDNPurgeCommandResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	updateTimeout, diags := data.Timeouts.Update(ctx, inttimeouts.DefaultUpdate)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, updateTimeout)
	defer cancel()

	apiResource := &client.CDNPurgeCommand{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: make(map[string]interface{}),
	}

	if !data.Description.IsNull() {
		apiResource.Metadata.Description = data.Description.ValueString()
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Labels = labels
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Annotations = annotations
	}

	// Marshal spec fields from Terraform state to API struct
	if data.HardPurge != nil {
		hard_purgeMap := make(map[string]interface{})
		apiResource.Spec["hard_purge"] = hard_purgeMap
	}
	if data.PurgeAll != nil {
		purge_allMap := make(map[string]interface{})
		apiResource.Spec["purge_all"] = purge_allMap
	}
	if data.SoftPurge != nil {
		soft_purgeMap := make(map[string]interface{})
		apiResource.Spec["soft_purge"] = soft_purgeMap
	}
	if data.VirtualHost != nil {
		virtual_hostMap := make(map[string]interface{})
		if !data.VirtualHost.Name.IsNull() && !data.VirtualHost.Name.IsUnknown() {
			virtual_hostMap["name"] = data.VirtualHost.Name.ValueString()
		}
		if !data.VirtualHost.Namespace.IsNull() && !data.VirtualHost.Namespace.IsUnknown() {
			virtual_hostMap["namespace"] = data.VirtualHost.Namespace.ValueString()
		}
		if !data.VirtualHost.Tenant.IsNull() && !data.VirtualHost.Tenant.IsUnknown() {
			virtual_hostMap["tenant"] = data.VirtualHost.Tenant.ValueString()
		}
		apiResource.Spec["virtual_host"] = virtual_hostMap
	}
	if !data.Hostname.IsNull() && !data.Hostname.IsUnknown() {
		apiResource.Spec["hostname"] = data.Hostname.ValueString()
	}
	if !data.Pattern.IsNull() && !data.Pattern.IsUnknown() {
		apiResource.Spec["pattern"] = data.Pattern.ValueString()
	}
	if !data.URLPath.IsNull() && !data.URLPath.IsUnknown() {
		apiResource.Spec["url_path"] = data.URLPath.ValueString()
	}

	_, err := r.client.UpdateCDNPurgeCommand(ctx, apiResource)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update CDNPurgeCommand: %s", err))
		return
	}

	// Use plan data for ID since API response may not include metadata.name
	data.ID = types.StringValue(data.Name.ValueString())

	// Fetch the resource to get complete state including computed fields
	// PUT responses may not include all computed nested fields (like tenant in Object Reference blocks)
	fetched, fetchErr := r.client.GetCDNPurgeCommand(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if fetchErr != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read CDNPurgeCommand after update: %s", fetchErr))
		return
	}

	// Set computed fields from API response
	if v, ok := fetched.Spec["hostname"].(string); ok && v != "" {
		data.Hostname = types.StringValue(v)
	} else if data.Hostname.IsUnknown() {
		// API didn't return value and plan was unknown - set to null
		data.Hostname = types.StringNull()
	}
	// If plan had a value, preserve it
	if v, ok := fetched.Spec["pattern"].(string); ok && v != "" {
		data.Pattern = types.StringValue(v)
	} else if data.Pattern.IsUnknown() {
		// API didn't return value and plan was unknown - set to null
		data.Pattern = types.StringNull()
	}
	// If plan had a value, preserve it
	if v, ok := fetched.Spec["url_path"].(string); ok && v != "" {
		data.URLPath = types.StringValue(v)
	} else if data.URLPath.IsUnknown() {
		// API didn't return value and plan was unknown - set to null
		data.URLPath = types.StringNull()
	}
	// If plan had a value, preserve it

	// Unmarshal spec fields from fetched resource to Terraform state
	apiResource = fetched // Use GET response which includes all computed fields
	isImport := false     // Update is never an import
	_ = isImport          // May be unused if resource has no blocks needing import detection
	if _, ok := apiResource.Spec["hard_purge"].(map[string]interface{}); ok && isImport && data.HardPurge == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.HardPurge = &CDNPurgeCommandEmptyModel{}
	}
	// Normal Read: preserve existing state value
	if _, ok := apiResource.Spec["purge_all"].(map[string]interface{}); ok && isImport && data.PurgeAll == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.PurgeAll = &CDNPurgeCommandEmptyModel{}
	}
	// Normal Read: preserve existing state value
	if _, ok := apiResource.Spec["soft_purge"].(map[string]interface{}); ok && isImport && data.SoftPurge == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.SoftPurge = &CDNPurgeCommandEmptyModel{}
	}
	// Normal Read: preserve existing state value
	if blockData, ok := apiResource.Spec["virtual_host"].(map[string]interface{}); ok && (isImport || data.VirtualHost != nil) {
		data.VirtualHost = &CDNPurgeCommandVirtualHostModel{
			Name: func() types.String {
				if v, ok := blockData["name"].(string); ok && v != "" {
					return types.StringValue(v)
				}
				return types.StringNull()
			}(),
			Namespace: func() types.String {
				if v, ok := blockData["namespace"].(string); ok && v != "" {
					return types.StringValue(v)
				}
				return types.StringNull()
			}(),
			Tenant: func() types.String {
				if v, ok := blockData["tenant"].(string); ok && v != "" {
					return types.StringValue(v)
				}
				return types.StringNull()
			}(),
		}
	}
	if v, ok := apiResource.Spec["hostname"].(string); ok && v != "" {
		data.Hostname = types.StringValue(v)
	} else {
		data.Hostname = types.StringNull()
	}
	if v, ok := apiResource.Spec["pattern"].(string); ok && v != "" {
		data.Pattern = types.StringValue(v)
	} else {
		data.Pattern = types.StringNull()
	}
	if v, ok := apiResource.Spec["url_path"].(string); ok && v != "" {
		data.URLPath = types.StringValue(v)
	} else {
		data.URLPath = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *CDNPurgeCommandResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data CDNPurgeCommandResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	deleteTimeout, diags := data.Timeouts.Delete(ctx, inttimeouts.DefaultDelete)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, deleteTimeout)
	defer cancel()
	err := r.client.DeleteCDNPurgeCommand(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		// If the resource is already gone, consider deletion successful (idempotent delete)
		if strings.Contains(err.Error(), "NOT_FOUND") || strings.Contains(err.Error(), "404") {
			tflog.Warn(ctx, "CDNPurgeCommand already deleted, removing from state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			return
		}
		// If delete is not implemented (501), warn and remove from state
		// Some F5 XC resources don't support deletion via API
		if strings.Contains(err.Error(), "501") {
			tflog.Warn(ctx, "CDNPurgeCommand delete not supported by API (501), removing from state only", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete CDNPurgeCommand: %s", err))
		return
	}
}

func (r *CDNPurgeCommandResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import ID format: namespace/name
	parts := strings.Split(req.ID, "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError(
			"Invalid Import ID",
			fmt.Sprintf("Expected import ID format: namespace/name, got: %s", req.ID),
		)
		return
	}
	namespace := parts[0]
	name := parts[1]

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("namespace"), namespace)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), name)...)

	// Set private state marker to indicate this is an import operation
	// This allows Read to populate all nested blocks from API response
	diags := resp.Private.SetKey(ctx, "isImport", []byte("true"))
	resp.Diagnostics.Append(diags...)
}
