// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification — read-only data source (GetSpecType only)

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/f5xc-salesdemos/terraform-provider-xcsh/internal/client"
)

var (
	_ datasource.DataSource              = &CertifiedHardwareDataSource{}
	_ datasource.DataSourceWithConfigure = &CertifiedHardwareDataSource{}
)

func NewCertifiedHardwareDataSource() datasource.DataSource {
	return &CertifiedHardwareDataSource{}
}

type CertifiedHardwareDataSource struct {
	client *client.Client
}

type CertifiedHardwareDataSourceModel struct {
	ID                    types.String `tfsdk:"id"`
	Name                  types.String `tfsdk:"name"`
	Namespace             types.String `tfsdk:"namespace"`
	Description           types.String `tfsdk:"description"`
	Labels                types.Map    `tfsdk:"labels"`
	Annotations           types.Map    `tfsdk:"annotations"`
	CertifiedHardwareType types.String `tfsdk:"certified_hardware_type"`
	Devices               types.String `tfsdk:"devices"`
	ImageList             types.String `tfsdk:"image_list"`
	InternalUsbDeviceRule types.String `tfsdk:"internal_usb_device_rule"`
	MemPageNumber         types.String `tfsdk:"mem_page_number"`
	MemPageSize           types.String `tfsdk:"mem_page_size"`
	NumaMem               types.String `tfsdk:"numa_mem"`
	NumaNodes             types.String `tfsdk:"numa_nodes"`
	VendorModelList       types.String `tfsdk:"vendor_model_list"`
}

func (d *CertifiedHardwareDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_certified_hardware"
}

func (d *CertifiedHardwareDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a Certified Hardware resource in F5 Distributed Cloud for get certified hardware object. configuration. (read-only data source)",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier.",
				Computed:            true,
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "Name of the CertifiedHardware to look up.",
				Required:            true,
			},
			"namespace": schema.StringAttribute{
				MarkdownDescription: "Namespace of the CertifiedHardware.",
				Required:            true,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Description.",
				Computed:            true,
			},
			"labels": schema.MapAttribute{
				MarkdownDescription: "Labels.",
				Computed:            true,
				ElementType:         types.StringType,
			},
			"annotations": schema.MapAttribute{
				MarkdownDescription: "Annotations.",
				Computed:            true,
				ElementType:         types.StringType,
			},
			"certified_hardware_type": schema.StringAttribute{
				MarkdownDescription: "[Enum: VOLTMESH|VOLTSTACK_COMBO|CLOUD_MARKET_PLACE] Different type of certified HW for billing rate. Possible values are `VOLTMESH`, `VOLTSTACK_COMBO`, `CLOUD_MARKET_PLACE`. Defaults to `VOLTMESH`.",
				Computed:            true,
			},
			"devices": schema.StringAttribute{
				MarkdownDescription: "List of supported devices in this model.",
				Computed:            true,
			},
			"image_list": schema.StringAttribute{
				MarkdownDescription: "List of image names with providers for this certified hardware, e.g. AWS ami-0f99d090261d2acd5.",
				Computed:            true,
			},
			"internal_usb_device_rule": schema.StringAttribute{
				MarkdownDescription: "List of internal USB device rules for server.",
				Computed:            true,
			},
			"mem_page_number": schema.StringAttribute{
				MarkdownDescription: "Number of pages allocated in this certified hardware for Hugepages. Each page size is defined above in 'mem_page_size' Total memory reserved for Hugepages is 'mem_page_size * mem_page_number'.",
				Computed:            true,
			},
			"mem_page_size": schema.StringAttribute{
				MarkdownDescription: "[Enum: HARDWARE_MEM_PAGE_SIZE_INVALID|HARDWARE_MEM_PAGE_SIZE_4KB|HARDWARE_MEM_PAGE_SIZE_2MB|HARDWARE_MEM_PAGE_SIZE_1GB] Memory for packets buffers etc are allocated in blocks of pages. Size of each memory page is defined here. Invalid Page size Page size of 4KB Page size of 2MB Page size of 1GB. Possible values are `HARDWARE_MEM_PAGE_SIZE_INVALID`, `HARDWARE_MEM_PAGE_SIZE_4KB`, `HARDWARE_MEM_PAGE_SIZE_2MB`, `HARDWARE_MEM_PAGE_SIZE_1GB`. Defaults to `HARDWARE_MEM_PAGE_SIZE_INVALID`.",
				Computed:            true,
			},
			"numa_mem": schema.StringAttribute{
				MarkdownDescription: "List of Numa nodes with the number of MB of instance memory to map to node instance If not specified, memory is evenly divided among available NUMA nodes.",
				Computed:            true,
			},
			"numa_nodes": schema.StringAttribute{
				MarkdownDescription: "The number of host NUMA nodes used in certified hardware.",
				Computed:            true,
			},
			"vendor_model_list": schema.StringAttribute{
				MarkdownDescription: "List of supported hardware vendor and model for this certified hardware.",
				Computed:            true,
			},
		},
	}
}

func (d *CertifiedHardwareDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Data Source Configure Type", "Expected *client.Client")
		return
	}
	d.client = client
}

func (d *CertifiedHardwareDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data CertifiedHardwareDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resource, err := d.client.GetCertifiedHardware(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read CertifiedHardware: %s", err))
		return
	}

	data.ID = types.StringValue(resource.Metadata.Name)
	data.Name = types.StringValue(resource.Metadata.Name)
	data.Namespace = types.StringValue(resource.Metadata.Namespace)
	if resource.Metadata.Description != "" {
		data.Description = types.StringValue(resource.Metadata.Description)
	} else {
		data.Description = types.StringNull()
	}

	if len(resource.Metadata.Labels) > 0 {
		filteredLabels := filterSystemLabels(resource.Metadata.Labels)
		if len(filteredLabels) > 0 {
			labels, diags := types.MapValueFrom(ctx, types.StringType, filteredLabels)
			resp.Diagnostics.Append(diags...)
			if !resp.Diagnostics.HasError() {
				data.Labels = labels
			}
		} else {
			data.Labels = types.MapNull(types.StringType)
		}
	} else {
		data.Labels = types.MapNull(types.StringType)
	}

	if len(resource.Metadata.Annotations) > 0 {
		annotations, diags := types.MapValueFrom(ctx, types.StringType, resource.Metadata.Annotations)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Annotations = annotations
		}
	} else {
		data.Annotations = types.MapNull(types.StringType)
	}

	// Map spec fields from API response
	if v, ok := resource.Spec["certified_hardware_type"]; ok && v != nil {
		data.CertifiedHardwareType = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.CertifiedHardwareType = types.StringNull()
	}
	if v, ok := resource.Spec["devices"]; ok && v != nil {
		data.Devices = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.Devices = types.StringNull()
	}
	if v, ok := resource.Spec["image_list"]; ok && v != nil {
		data.ImageList = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.ImageList = types.StringNull()
	}
	if v, ok := resource.Spec["internal_usb_device_rule"]; ok && v != nil {
		data.InternalUsbDeviceRule = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.InternalUsbDeviceRule = types.StringNull()
	}
	if v, ok := resource.Spec["mem_page_number"]; ok && v != nil {
		data.MemPageNumber = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.MemPageNumber = types.StringNull()
	}
	if v, ok := resource.Spec["mem_page_size"]; ok && v != nil {
		data.MemPageSize = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.MemPageSize = types.StringNull()
	}
	if v, ok := resource.Spec["numa_mem"]; ok && v != nil {
		data.NumaMem = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.NumaMem = types.StringNull()
	}
	if v, ok := resource.Spec["numa_nodes"]; ok && v != nil {
		data.NumaNodes = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.NumaNodes = types.StringNull()
	}
	if v, ok := resource.Spec["vendor_model_list"]; ok && v != nil {
		data.VendorModelList = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.VendorModelList = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
