// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification — read-only data source (GetSpecType only)

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/f5xc-salesdemos/terraform-provider-f5xc/internal/client"
)

var (
	_ datasource.DataSource              = &FlowAnomalyDataSource{}
	_ datasource.DataSourceWithConfigure = &FlowAnomalyDataSource{}
)

func NewFlowAnomalyDataSource() datasource.DataSource {
	return &FlowAnomalyDataSource{}
}

type FlowAnomalyDataSource struct {
	client *client.Client
}

type FlowAnomalyDataSourceModel struct {
	ID              types.String `tfsdk:"id"`
	Name            types.String `tfsdk:"name"`
	Namespace       types.String `tfsdk:"namespace"`
	Description     types.String `tfsdk:"description"`
	Labels          types.Map    `tfsdk:"labels"`
	Annotations     types.Map    `tfsdk:"annotations"`
	LastEnabledTime types.String `tfsdk:"last_enabled_time"`
	ServiceState    types.String `tfsdk:"service_state"`
}

func (d *FlowAnomalyDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_flow_anomaly"
}

func (d *FlowAnomalyDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a Flow Anomaly resource in F5 Distributed Cloud for flow anomaly specification. configuration. (read-only data source)",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier.",
				Computed:            true,
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "Name of the FlowAnomaly to look up.",
				Required:            true,
			},
			"namespace": schema.StringAttribute{
				MarkdownDescription: "Namespace of the FlowAnomaly.",
				Required:            true,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Description.",
				Computed:            true,
			},
			"labels": schema.MapAttribute{
				MarkdownDescription: "Labels.",
				Computed:            true,
				ElementType:         types.StringType,
			},
			"annotations": schema.MapAttribute{
				MarkdownDescription: "Annotations.",
				Computed:            true,
				ElementType:         types.StringType,
			},
			"last_enabled_time": schema.StringAttribute{
				MarkdownDescription: "Last enabled time for flow anomaly add on service.",
				Computed:            true,
			},
			"service_state": schema.StringAttribute{
				MarkdownDescription: "[Enum: AS_NONE|AS_PENDING|AS_SUBSCRIBED|AS_ERROR] X-displayName: 'Addon Service State' State of a service - AS_NONE: x-displayName: 'None' default state - AS_PENDING: x-displayName: 'Pending Subscription' initiated subscription request and is pending to activate (requested). - AS_SUBSCRIBED: x-displayName: 'Subscribed' successfully subscribed .. Possible values are `AS_NONE`, `AS_PENDING`, `AS_SUBSCRIBED`, `AS_ERROR`. Defaults to `AS_NONE`.",
				Computed:            true,
			},
		},
	}
}

func (d *FlowAnomalyDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Data Source Configure Type", "Expected *client.Client")
		return
	}
	d.client = client
}

func (d *FlowAnomalyDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data FlowAnomalyDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resource, err := d.client.GetFlowAnomaly(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read FlowAnomaly: %s", err))
		return
	}

	data.ID = types.StringValue(resource.Metadata.Name)
	data.Name = types.StringValue(resource.Metadata.Name)
	data.Namespace = types.StringValue(resource.Metadata.Namespace)
	if resource.Metadata.Description != "" {
		data.Description = types.StringValue(resource.Metadata.Description)
	} else {
		data.Description = types.StringNull()
	}

	if len(resource.Metadata.Labels) > 0 {
		filteredLabels := filterSystemLabels(resource.Metadata.Labels)
		if len(filteredLabels) > 0 {
			labels, diags := types.MapValueFrom(ctx, types.StringType, filteredLabels)
			resp.Diagnostics.Append(diags...)
			if !resp.Diagnostics.HasError() {
				data.Labels = labels
			}
		} else {
			data.Labels = types.MapNull(types.StringType)
		}
	} else {
		data.Labels = types.MapNull(types.StringType)
	}

	if len(resource.Metadata.Annotations) > 0 {
		annotations, diags := types.MapValueFrom(ctx, types.StringType, resource.Metadata.Annotations)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Annotations = annotations
		}
	} else {
		data.Annotations = types.MapNull(types.StringType)
	}

	// Map spec fields from API response
	if v, ok := resource.Spec["last_enabled_time"]; ok && v != nil {
		data.LastEnabledTime = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.LastEnabledTime = types.StringNull()
	}
	if v, ok := resource.Spec["service_state"]; ok && v != nil {
		data.ServiceState = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.ServiceState = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
