// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/f5xc-salesdemos/terraform-provider-f5xc/internal/client"
	inttimeouts "github.com/f5xc-salesdemos/terraform-provider-f5xc/internal/timeouts"
	"github.com/f5xc-salesdemos/terraform-provider-f5xc/internal/validators"
)

// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource                   = &IKEPhase1ProfileResource{}
	_ resource.ResourceWithConfigure      = &IKEPhase1ProfileResource{}
	_ resource.ResourceWithImportState    = &IKEPhase1ProfileResource{}
	_ resource.ResourceWithModifyPlan     = &IKEPhase1ProfileResource{}
	_ resource.ResourceWithValidateConfig = &IKEPhase1ProfileResource{}
)

func NewIKEPhase1ProfileResource() resource.Resource {
	return &IKEPhase1ProfileResource{}
}

type IKEPhase1ProfileResource struct {
	client *client.Client
}

// IKEPhase1ProfileEmptyModel represents empty nested blocks
type IKEPhase1ProfileEmptyModel struct {
}

// IKEPhase1ProfileIKEKeylifetimeHoursModel represents ike_keylifetime_hours block
type IKEPhase1ProfileIKEKeylifetimeHoursModel struct {
	Duration types.Int64 `tfsdk:"duration"`
}

// IKEPhase1ProfileIKEKeylifetimeHoursModelAttrTypes defines the attribute types for IKEPhase1ProfileIKEKeylifetimeHoursModel
var IKEPhase1ProfileIKEKeylifetimeHoursModelAttrTypes = map[string]attr.Type{
	"duration": types.Int64Type,
}

// IKEPhase1ProfileIKEKeylifetimeMinutesModel represents ike_keylifetime_minutes block
type IKEPhase1ProfileIKEKeylifetimeMinutesModel struct {
	Duration types.Int64 `tfsdk:"duration"`
}

// IKEPhase1ProfileIKEKeylifetimeMinutesModelAttrTypes defines the attribute types for IKEPhase1ProfileIKEKeylifetimeMinutesModel
var IKEPhase1ProfileIKEKeylifetimeMinutesModelAttrTypes = map[string]attr.Type{
	"duration": types.Int64Type,
}

// IKEPhase1ProfileReauthTimeoutDaysModel represents reauth_timeout_days block
type IKEPhase1ProfileReauthTimeoutDaysModel struct {
	Duration types.Int64 `tfsdk:"duration"`
}

// IKEPhase1ProfileReauthTimeoutDaysModelAttrTypes defines the attribute types for IKEPhase1ProfileReauthTimeoutDaysModel
var IKEPhase1ProfileReauthTimeoutDaysModelAttrTypes = map[string]attr.Type{
	"duration": types.Int64Type,
}

// IKEPhase1ProfileReauthTimeoutHoursModel represents reauth_timeout_hours block
type IKEPhase1ProfileReauthTimeoutHoursModel struct {
	Duration types.Int64 `tfsdk:"duration"`
}

// IKEPhase1ProfileReauthTimeoutHoursModelAttrTypes defines the attribute types for IKEPhase1ProfileReauthTimeoutHoursModel
var IKEPhase1ProfileReauthTimeoutHoursModelAttrTypes = map[string]attr.Type{
	"duration": types.Int64Type,
}

type IKEPhase1ProfileResourceModel struct {
	Name                  types.String                                `tfsdk:"name"`
	Namespace             types.String                                `tfsdk:"namespace"`
	AuthenticationAlgos   types.List                                  `tfsdk:"authentication_algos"`
	DhGroup               types.List                                  `tfsdk:"dh_group"`
	EncryptionAlgos       types.List                                  `tfsdk:"encryption_algos"`
	Prf                   types.List                                  `tfsdk:"prf"`
	Annotations           types.Map                                   `tfsdk:"annotations"`
	Description           types.String                                `tfsdk:"description"`
	Disable               types.Bool                                  `tfsdk:"disable"`
	Labels                types.Map                                   `tfsdk:"labels"`
	ID                    types.String                                `tfsdk:"id"`
	Timeouts              timeouts.Value                              `tfsdk:"timeouts"`
	IKEKeylifetimeHours   *IKEPhase1ProfileIKEKeylifetimeHoursModel   `tfsdk:"ike_keylifetime_hours"`
	IKEKeylifetimeMinutes *IKEPhase1ProfileIKEKeylifetimeMinutesModel `tfsdk:"ike_keylifetime_minutes"`
	ReauthDisabled        *IKEPhase1ProfileEmptyModel                 `tfsdk:"reauth_disabled"`
	ReauthTimeoutDays     *IKEPhase1ProfileReauthTimeoutDaysModel     `tfsdk:"reauth_timeout_days"`
	ReauthTimeoutHours    *IKEPhase1ProfileReauthTimeoutHoursModel    `tfsdk:"reauth_timeout_hours"`
	UseDefaultKeylifetime *IKEPhase1ProfileEmptyModel                 `tfsdk:"use_default_keylifetime"`
}

func (r *IKEPhase1ProfileResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_ike_phase1_profile"
}

func (r *IKEPhase1ProfileResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a IKE Phase1 Profile resource in F5 Distributed Cloud for ike phase1 profile specification. configuration.",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				MarkdownDescription: "Name of the IKE Phase1 Profile. Must be unique within the namespace.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.NameValidator(),
				},
			},
			"namespace": schema.StringAttribute{
				MarkdownDescription: "Namespace where the IKE Phase1 Profile will be created.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.NamespaceValidator(),
				},
			},
			"authentication_algos": schema.ListAttribute{
				MarkdownDescription: "[Enum: AUTH_ALG_DEFAULT|SHA256_HMAC|SHA384_HMAC|SHA512_HMAC|AUTH_ALG_NONE] Choose one or more Authentication Algorithm. Use None option when using the aes-gcm or aes-ccm encryption algorithms. Possible values are `AUTH_ALG_DEFAULT`, `SHA256_HMAC`, `SHA384_HMAC`, `SHA512_HMAC`, `AUTH_ALG_NONE`. Defaults to `AUTH_ALG_DEFAULT`.",
				Required:            true,
				ElementType:         types.StringType,
			},
			"dh_group": schema.ListAttribute{
				MarkdownDescription: "[Enum: DH_GROUP_DEFAULT|DH_GROUP_14|DH_GROUP_15|DH_GROUP_16|DH_GROUP_17|DH_GROUP_18|DH_GROUP_19|DH_GROUP_20|DH_GROUP_21|DH_GROUP_26] Choose the acceptable Diffie Hellman (DH) Group or Groups that you are willing to accept as part of this profile. Possible values are `DH_GROUP_DEFAULT`, `DH_GROUP_14`, `DH_GROUP_15`, `DH_GROUP_16`, `DH_GROUP_17`, `DH_GROUP_18`, `DH_GROUP_19`, `DH_GROUP_20`, `DH_GROUP_21`, `DH_GROUP_26`. Defaults to `DH_GROUP_DEFAULT`.",
				Required:            true,
				ElementType:         types.StringType,
			},
			"encryption_algos": schema.ListAttribute{
				MarkdownDescription: "[Enum: ENC_ALG_DEFAULT|AES128_CBC|AES192_CBC|AES256_CBC|TRIPLE_DES_CBC|AES128_GCM|AES192_GCM|AES256_GCM] Choose one or more encryption algorithms. Possible values are `ENC_ALG_DEFAULT`, `AES128_CBC`, `AES192_CBC`, `AES256_CBC`, `TRIPLE_DES_CBC`, `AES128_GCM`, `AES192_GCM`, `AES256_GCM`. Defaults to `ENC_ALG_DEFAULT`.",
				Required:            true,
				ElementType:         types.StringType,
			},
			"prf": schema.ListAttribute{
				MarkdownDescription: "[Enum: PRF_DEFAULT|PRFSHA256|PRFSHA384|PRFSHA512] Select PseudoRandomFunction for IKE SA. Possible values are `PRF_DEFAULT`, `PRFSHA256`, `PRFSHA384`, `PRFSHA512`. Defaults to `PRF_DEFAULT`.",
				Required:            true,
				ElementType:         types.StringType,
			},
			"annotations": schema.MapAttribute{
				MarkdownDescription: "Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Human readable description for the object.",
				Optional:            true,
			},
			"disable": schema.BoolAttribute{
				MarkdownDescription: "A value of true will administratively disable the object.",
				Optional:            true,
			},
			"labels": schema.MapAttribute{
				MarkdownDescription: "Labels is a user defined key value map that can be attached to resources for organization and filtering.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier for the resource.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
		Blocks: map[string]schema.Block{
			"timeouts": timeouts.Block(ctx, timeouts.Opts{
				Create: true,
				Read:   true,
				Update: true,
				Delete: true,
			}),
			"ike_keylifetime_hours": schema.SingleNestedBlock{
				MarkdownDescription: "[OneOf: ike_keylifetime_hours, ike_keylifetime_minutes, use_default_keylifetime; Default: use_default_keylifetime] Configuration parameter for ike keylifetime hours.",
				Attributes: map[string]schema.Attribute{
					"duration": schema.Int64Attribute{
						MarkdownDescription: "Duration. Configuration parameter for duration",
						Optional:            true,
					},
				},
			},
			"ike_keylifetime_minutes": schema.SingleNestedBlock{
				MarkdownDescription: "Configuration parameter for ike keylifetime minutes.",
				Attributes: map[string]schema.Attribute{
					"duration": schema.Int64Attribute{
						MarkdownDescription: "Duration. Configuration parameter for duration",
						Optional:            true,
					},
				},
			},
			"reauth_disabled": schema.SingleNestedBlock{
				MarkdownDescription: "[OneOf: reauth_disabled, reauth_timeout_days, reauth_timeout_hours] Enable this option",
			},
			"reauth_timeout_days": schema.SingleNestedBlock{
				MarkdownDescription: "Configuration parameter for reauth timeout days.",
				Attributes: map[string]schema.Attribute{
					"duration": schema.Int64Attribute{
						MarkdownDescription: "Duration. Configuration parameter for duration",
						Optional:            true,
					},
				},
			},
			"reauth_timeout_hours": schema.SingleNestedBlock{
				MarkdownDescription: "Configuration parameter for reauth timeout hours.",
				Attributes: map[string]schema.Attribute{
					"duration": schema.Int64Attribute{
						MarkdownDescription: "Duration. Configuration parameter for duration",
						Optional:            true,
					},
				},
			},
			"use_default_keylifetime": schema.SingleNestedBlock{
				MarkdownDescription: "Configuration parameter for use default keylifetime.",
			},
		},
	}
}

func (r *IKEPhase1ProfileResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.client = client
}

// ValidateConfig implements resource.ResourceWithValidateConfig
func (r *IKEPhase1ProfileResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var data IKEPhase1ProfileResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
}

// ModifyPlan implements resource.ResourceWithModifyPlan
func (r *IKEPhase1ProfileResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() {
		resp.Diagnostics.AddWarning(
			"Resource Destruction",
			"This will permanently delete the ike_phase1_profile from F5 Distributed Cloud.",
		)
		return
	}

	if req.State.Raw.IsNull() {
		var plan IKEPhase1ProfileResourceModel
		resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
		if resp.Diagnostics.HasError() {
			return
		}

		if plan.Name.IsUnknown() {
			resp.Diagnostics.AddWarning(
				"Unknown Resource Name",
				"The resource name is not yet known. This may affect planning for dependent resources.",
			)
		}
	}
}

func (r *IKEPhase1ProfileResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data IKEPhase1ProfileResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createTimeout, diags := data.Timeouts.Create(ctx, inttimeouts.DefaultCreate)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, createTimeout)
	defer cancel()

	tflog.Debug(ctx, "Creating ike_phase1_profile", map[string]interface{}{
		"name":      data.Name.ValueString(),
		"namespace": data.Namespace.ValueString(),
	})

	createReq := &client.IKEPhase1Profile{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: make(map[string]interface{}),
	}

	if !data.Description.IsNull() {
		createReq.Metadata.Description = data.Description.ValueString()
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.Metadata.Labels = labels
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.Metadata.Annotations = annotations
	}

	// Marshal spec fields from Terraform state to API struct
	if !data.AuthenticationAlgos.IsNull() && !data.AuthenticationAlgos.IsUnknown() {
		var authentication_algosList []string
		resp.Diagnostics.Append(data.AuthenticationAlgos.ElementsAs(ctx, &authentication_algosList, false)...)
		if !resp.Diagnostics.HasError() {
			createReq.Spec["authentication_algos"] = authentication_algosList
		}
	}
	if !data.DhGroup.IsNull() && !data.DhGroup.IsUnknown() {
		var dh_groupList []string
		resp.Diagnostics.Append(data.DhGroup.ElementsAs(ctx, &dh_groupList, false)...)
		if !resp.Diagnostics.HasError() {
			createReq.Spec["dh_group"] = dh_groupList
		}
	}
	if !data.EncryptionAlgos.IsNull() && !data.EncryptionAlgos.IsUnknown() {
		var encryption_algosList []string
		resp.Diagnostics.Append(data.EncryptionAlgos.ElementsAs(ctx, &encryption_algosList, false)...)
		if !resp.Diagnostics.HasError() {
			createReq.Spec["encryption_algos"] = encryption_algosList
		}
	}
	if !data.Prf.IsNull() && !data.Prf.IsUnknown() {
		var prfList []string
		resp.Diagnostics.Append(data.Prf.ElementsAs(ctx, &prfList, false)...)
		if !resp.Diagnostics.HasError() {
			createReq.Spec["prf"] = prfList
		}
	}
	if data.IKEKeylifetimeHours != nil {
		ike_keylifetime_hoursMap := make(map[string]interface{})
		if !data.IKEKeylifetimeHours.Duration.IsNull() && !data.IKEKeylifetimeHours.Duration.IsUnknown() {
			ike_keylifetime_hoursMap["duration"] = data.IKEKeylifetimeHours.Duration.ValueInt64()
		}
		createReq.Spec["ike_keylifetime_hours"] = ike_keylifetime_hoursMap
	}
	if data.IKEKeylifetimeMinutes != nil {
		ike_keylifetime_minutesMap := make(map[string]interface{})
		if !data.IKEKeylifetimeMinutes.Duration.IsNull() && !data.IKEKeylifetimeMinutes.Duration.IsUnknown() {
			ike_keylifetime_minutesMap["duration"] = data.IKEKeylifetimeMinutes.Duration.ValueInt64()
		}
		createReq.Spec["ike_keylifetime_minutes"] = ike_keylifetime_minutesMap
	}
	if data.ReauthDisabled != nil {
		reauth_disabledMap := make(map[string]interface{})
		createReq.Spec["reauth_disabled"] = reauth_disabledMap
	}
	if data.ReauthTimeoutDays != nil {
		reauth_timeout_daysMap := make(map[string]interface{})
		if !data.ReauthTimeoutDays.Duration.IsNull() && !data.ReauthTimeoutDays.Duration.IsUnknown() {
			reauth_timeout_daysMap["duration"] = data.ReauthTimeoutDays.Duration.ValueInt64()
		}
		createReq.Spec["reauth_timeout_days"] = reauth_timeout_daysMap
	}
	if data.ReauthTimeoutHours != nil {
		reauth_timeout_hoursMap := make(map[string]interface{})
		if !data.ReauthTimeoutHours.Duration.IsNull() && !data.ReauthTimeoutHours.Duration.IsUnknown() {
			reauth_timeout_hoursMap["duration"] = data.ReauthTimeoutHours.Duration.ValueInt64()
		}
		createReq.Spec["reauth_timeout_hours"] = reauth_timeout_hoursMap
	}
	if data.UseDefaultKeylifetime != nil {
		use_default_keylifetimeMap := make(map[string]interface{})
		createReq.Spec["use_default_keylifetime"] = use_default_keylifetimeMap
	}

	apiResource, err := r.client.CreateIKEPhase1Profile(ctx, createReq)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create IKEPhase1Profile: %s", err))
		return
	}

	data.ID = types.StringValue(apiResource.Metadata.Name)

	// Unmarshal spec fields from API response to Terraform state
	// This ensures computed nested fields (like tenant in Object Reference blocks) have known values
	isImport := false // Create is never an import
	_ = isImport      // May be unused if resource has no blocks needing import detection
	if v, ok := apiResource.Spec["authentication_algos"].([]interface{}); ok && len(v) > 0 {
		var authentication_algosList []string
		for _, item := range v {
			if s, ok := item.(string); ok {
				authentication_algosList = append(authentication_algosList, s)
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.StringType, authentication_algosList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.AuthenticationAlgos = listVal
		}
	} else {
		data.AuthenticationAlgos = types.ListNull(types.StringType)
	}
	if v, ok := apiResource.Spec["dh_group"].([]interface{}); ok && len(v) > 0 {
		var dh_groupList []string
		for _, item := range v {
			if s, ok := item.(string); ok {
				dh_groupList = append(dh_groupList, s)
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.StringType, dh_groupList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.DhGroup = listVal
		}
	} else {
		data.DhGroup = types.ListNull(types.StringType)
	}
	if v, ok := apiResource.Spec["encryption_algos"].([]interface{}); ok && len(v) > 0 {
		var encryption_algosList []string
		for _, item := range v {
			if s, ok := item.(string); ok {
				encryption_algosList = append(encryption_algosList, s)
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.StringType, encryption_algosList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.EncryptionAlgos = listVal
		}
	} else {
		data.EncryptionAlgos = types.ListNull(types.StringType)
	}
	if v, ok := apiResource.Spec["prf"].([]interface{}); ok && len(v) > 0 {
		var prfList []string
		for _, item := range v {
			if s, ok := item.(string); ok {
				prfList = append(prfList, s)
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.StringType, prfList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Prf = listVal
		}
	} else {
		data.Prf = types.ListNull(types.StringType)
	}
	if blockData, ok := apiResource.Spec["ike_keylifetime_hours"].(map[string]interface{}); ok && (isImport || data.IKEKeylifetimeHours != nil) {
		data.IKEKeylifetimeHours = &IKEPhase1ProfileIKEKeylifetimeHoursModel{
			Duration: func() types.Int64 {
				if !isImport && data.IKEKeylifetimeHours != nil {
					// Preserve existing state (null or user-set value)
					// This prevents API defaults (like 0) from overwriting user intent
					return data.IKEKeylifetimeHours.Duration
				}
				if !isImport {
					// Block not in user config - return null, not API default
					return types.Int64Null()
				}
				// Import case: read from API
				if v, ok := blockData["duration"].(float64); ok {
					return types.Int64Value(int64(v))
				}
				return types.Int64Null()
			}(),
		}
	}
	if blockData, ok := apiResource.Spec["ike_keylifetime_minutes"].(map[string]interface{}); ok && (isImport || data.IKEKeylifetimeMinutes != nil) {
		data.IKEKeylifetimeMinutes = &IKEPhase1ProfileIKEKeylifetimeMinutesModel{
			Duration: func() types.Int64 {
				if !isImport && data.IKEKeylifetimeMinutes != nil {
					// Preserve existing state (null or user-set value)
					// This prevents API defaults (like 0) from overwriting user intent
					return data.IKEKeylifetimeMinutes.Duration
				}
				if !isImport {
					// Block not in user config - return null, not API default
					return types.Int64Null()
				}
				// Import case: read from API
				if v, ok := blockData["duration"].(float64); ok {
					return types.Int64Value(int64(v))
				}
				return types.Int64Null()
			}(),
		}
	}
	if _, ok := apiResource.Spec["reauth_disabled"].(map[string]interface{}); ok && isImport && data.ReauthDisabled == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.ReauthDisabled = &IKEPhase1ProfileEmptyModel{}
	}
	// Normal Read: preserve existing state value
	if blockData, ok := apiResource.Spec["reauth_timeout_days"].(map[string]interface{}); ok && (isImport || data.ReauthTimeoutDays != nil) {
		data.ReauthTimeoutDays = &IKEPhase1ProfileReauthTimeoutDaysModel{
			Duration: func() types.Int64 {
				if !isImport && data.ReauthTimeoutDays != nil {
					// Preserve existing state (null or user-set value)
					// This prevents API defaults (like 0) from overwriting user intent
					return data.ReauthTimeoutDays.Duration
				}
				if !isImport {
					// Block not in user config - return null, not API default
					return types.Int64Null()
				}
				// Import case: read from API
				if v, ok := blockData["duration"].(float64); ok {
					return types.Int64Value(int64(v))
				}
				return types.Int64Null()
			}(),
		}
	}
	if blockData, ok := apiResource.Spec["reauth_timeout_hours"].(map[string]interface{}); ok && (isImport || data.ReauthTimeoutHours != nil) {
		data.ReauthTimeoutHours = &IKEPhase1ProfileReauthTimeoutHoursModel{
			Duration: func() types.Int64 {
				if !isImport && data.ReauthTimeoutHours != nil {
					// Preserve existing state (null or user-set value)
					// This prevents API defaults (like 0) from overwriting user intent
					return data.ReauthTimeoutHours.Duration
				}
				if !isImport {
					// Block not in user config - return null, not API default
					return types.Int64Null()
				}
				// Import case: read from API
				if v, ok := blockData["duration"].(float64); ok {
					return types.Int64Value(int64(v))
				}
				return types.Int64Null()
			}(),
		}
	}
	if _, ok := apiResource.Spec["use_default_keylifetime"].(map[string]interface{}); ok && isImport && data.UseDefaultKeylifetime == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.UseDefaultKeylifetime = &IKEPhase1ProfileEmptyModel{}
	}
	// Normal Read: preserve existing state value

	tflog.Trace(ctx, "created IKEPhase1Profile resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *IKEPhase1ProfileResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data IKEPhase1ProfileResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	readTimeout, diags := data.Timeouts.Read(ctx, inttimeouts.DefaultRead)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, readTimeout)
	defer cancel()

	apiResource, err := r.client.GetIKEPhase1Profile(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		// Check if the resource was deleted outside Terraform
		if strings.Contains(err.Error(), "NOT_FOUND") || strings.Contains(err.Error(), "404") {
			tflog.Warn(ctx, "IKEPhase1Profile not found, removing from state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read IKEPhase1Profile: %s", err))
		return
	}

	data.ID = types.StringValue(apiResource.Metadata.Name)
	data.Name = types.StringValue(apiResource.Metadata.Name)
	data.Namespace = types.StringValue(apiResource.Metadata.Namespace)

	// Read description from metadata
	if apiResource.Metadata.Description != "" {
		data.Description = types.StringValue(apiResource.Metadata.Description)
	} else {
		data.Description = types.StringNull()
	}

	// Filter out system-managed labels (ves.io/*) that are injected by the platform
	if len(apiResource.Metadata.Labels) > 0 {
		filteredLabels := filterSystemLabels(apiResource.Metadata.Labels)
		if len(filteredLabels) > 0 {
			labels, diags := types.MapValueFrom(ctx, types.StringType, filteredLabels)
			resp.Diagnostics.Append(diags...)
			if !resp.Diagnostics.HasError() {
				data.Labels = labels
			}
		} else {
			data.Labels = types.MapNull(types.StringType)
		}
	} else {
		data.Labels = types.MapNull(types.StringType)
	}

	if len(apiResource.Metadata.Annotations) > 0 {
		annotations, diags := types.MapValueFrom(ctx, types.StringType, apiResource.Metadata.Annotations)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Annotations = annotations
		}
	} else {
		data.Annotations = types.MapNull(types.StringType)
	}

	// Check if this Read is triggered by an import operation
	// Import sets a private state marker so we know to populate all nested blocks from API response
	isImport := false
	if importMarker, diags := req.Private.GetKey(ctx, "isImport"); diags.HasError() == false && string(importMarker) == "true" {
		isImport = true
	}
	_ = isImport // May be unused if resource has no blocks needing import detection
	if v, ok := apiResource.Spec["authentication_algos"].([]interface{}); ok && len(v) > 0 {
		var authentication_algosList []string
		for _, item := range v {
			if s, ok := item.(string); ok {
				authentication_algosList = append(authentication_algosList, s)
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.StringType, authentication_algosList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.AuthenticationAlgos = listVal
		}
	} else {
		data.AuthenticationAlgos = types.ListNull(types.StringType)
	}
	if v, ok := apiResource.Spec["dh_group"].([]interface{}); ok && len(v) > 0 {
		var dh_groupList []string
		for _, item := range v {
			if s, ok := item.(string); ok {
				dh_groupList = append(dh_groupList, s)
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.StringType, dh_groupList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.DhGroup = listVal
		}
	} else {
		data.DhGroup = types.ListNull(types.StringType)
	}
	if v, ok := apiResource.Spec["encryption_algos"].([]interface{}); ok && len(v) > 0 {
		var encryption_algosList []string
		for _, item := range v {
			if s, ok := item.(string); ok {
				encryption_algosList = append(encryption_algosList, s)
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.StringType, encryption_algosList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.EncryptionAlgos = listVal
		}
	} else {
		data.EncryptionAlgos = types.ListNull(types.StringType)
	}
	if v, ok := apiResource.Spec["prf"].([]interface{}); ok && len(v) > 0 {
		var prfList []string
		for _, item := range v {
			if s, ok := item.(string); ok {
				prfList = append(prfList, s)
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.StringType, prfList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Prf = listVal
		}
	} else {
		data.Prf = types.ListNull(types.StringType)
	}
	if blockData, ok := apiResource.Spec["ike_keylifetime_hours"].(map[string]interface{}); ok && (isImport || data.IKEKeylifetimeHours != nil) {
		data.IKEKeylifetimeHours = &IKEPhase1ProfileIKEKeylifetimeHoursModel{
			Duration: func() types.Int64 {
				if !isImport && data.IKEKeylifetimeHours != nil {
					// Preserve existing state (null or user-set value)
					// This prevents API defaults (like 0) from overwriting user intent
					return data.IKEKeylifetimeHours.Duration
				}
				if !isImport {
					// Block not in user config - return null, not API default
					return types.Int64Null()
				}
				// Import case: read from API
				if v, ok := blockData["duration"].(float64); ok {
					return types.Int64Value(int64(v))
				}
				return types.Int64Null()
			}(),
		}
	}
	if blockData, ok := apiResource.Spec["ike_keylifetime_minutes"].(map[string]interface{}); ok && (isImport || data.IKEKeylifetimeMinutes != nil) {
		data.IKEKeylifetimeMinutes = &IKEPhase1ProfileIKEKeylifetimeMinutesModel{
			Duration: func() types.Int64 {
				if !isImport && data.IKEKeylifetimeMinutes != nil {
					// Preserve existing state (null or user-set value)
					// This prevents API defaults (like 0) from overwriting user intent
					return data.IKEKeylifetimeMinutes.Duration
				}
				if !isImport {
					// Block not in user config - return null, not API default
					return types.Int64Null()
				}
				// Import case: read from API
				if v, ok := blockData["duration"].(float64); ok {
					return types.Int64Value(int64(v))
				}
				return types.Int64Null()
			}(),
		}
	}
	if _, ok := apiResource.Spec["reauth_disabled"].(map[string]interface{}); ok && isImport && data.ReauthDisabled == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.ReauthDisabled = &IKEPhase1ProfileEmptyModel{}
	}
	// Normal Read: preserve existing state value
	if blockData, ok := apiResource.Spec["reauth_timeout_days"].(map[string]interface{}); ok && (isImport || data.ReauthTimeoutDays != nil) {
		data.ReauthTimeoutDays = &IKEPhase1ProfileReauthTimeoutDaysModel{
			Duration: func() types.Int64 {
				if !isImport && data.ReauthTimeoutDays != nil {
					// Preserve existing state (null or user-set value)
					// This prevents API defaults (like 0) from overwriting user intent
					return data.ReauthTimeoutDays.Duration
				}
				if !isImport {
					// Block not in user config - return null, not API default
					return types.Int64Null()
				}
				// Import case: read from API
				if v, ok := blockData["duration"].(float64); ok {
					return types.Int64Value(int64(v))
				}
				return types.Int64Null()
			}(),
		}
	}
	if blockData, ok := apiResource.Spec["reauth_timeout_hours"].(map[string]interface{}); ok && (isImport || data.ReauthTimeoutHours != nil) {
		data.ReauthTimeoutHours = &IKEPhase1ProfileReauthTimeoutHoursModel{
			Duration: func() types.Int64 {
				if !isImport && data.ReauthTimeoutHours != nil {
					// Preserve existing state (null or user-set value)
					// This prevents API defaults (like 0) from overwriting user intent
					return data.ReauthTimeoutHours.Duration
				}
				if !isImport {
					// Block not in user config - return null, not API default
					return types.Int64Null()
				}
				// Import case: read from API
				if v, ok := blockData["duration"].(float64); ok {
					return types.Int64Value(int64(v))
				}
				return types.Int64Null()
			}(),
		}
	}
	if _, ok := apiResource.Spec["use_default_keylifetime"].(map[string]interface{}); ok && isImport && data.UseDefaultKeylifetime == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.UseDefaultKeylifetime = &IKEPhase1ProfileEmptyModel{}
	}
	// Normal Read: preserve existing state value

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *IKEPhase1ProfileResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data IKEPhase1ProfileResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	updateTimeout, diags := data.Timeouts.Update(ctx, inttimeouts.DefaultUpdate)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, updateTimeout)
	defer cancel()

	apiResource := &client.IKEPhase1Profile{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: make(map[string]interface{}),
	}

	if !data.Description.IsNull() {
		apiResource.Metadata.Description = data.Description.ValueString()
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Labels = labels
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Annotations = annotations
	}

	// Marshal spec fields from Terraform state to API struct
	if !data.AuthenticationAlgos.IsNull() && !data.AuthenticationAlgos.IsUnknown() {
		var authentication_algosList []string
		resp.Diagnostics.Append(data.AuthenticationAlgos.ElementsAs(ctx, &authentication_algosList, false)...)
		if !resp.Diagnostics.HasError() {
			apiResource.Spec["authentication_algos"] = authentication_algosList
		}
	}
	if !data.DhGroup.IsNull() && !data.DhGroup.IsUnknown() {
		var dh_groupList []string
		resp.Diagnostics.Append(data.DhGroup.ElementsAs(ctx, &dh_groupList, false)...)
		if !resp.Diagnostics.HasError() {
			apiResource.Spec["dh_group"] = dh_groupList
		}
	}
	if !data.EncryptionAlgos.IsNull() && !data.EncryptionAlgos.IsUnknown() {
		var encryption_algosList []string
		resp.Diagnostics.Append(data.EncryptionAlgos.ElementsAs(ctx, &encryption_algosList, false)...)
		if !resp.Diagnostics.HasError() {
			apiResource.Spec["encryption_algos"] = encryption_algosList
		}
	}
	if !data.Prf.IsNull() && !data.Prf.IsUnknown() {
		var prfList []string
		resp.Diagnostics.Append(data.Prf.ElementsAs(ctx, &prfList, false)...)
		if !resp.Diagnostics.HasError() {
			apiResource.Spec["prf"] = prfList
		}
	}
	if data.IKEKeylifetimeHours != nil {
		ike_keylifetime_hoursMap := make(map[string]interface{})
		if !data.IKEKeylifetimeHours.Duration.IsNull() && !data.IKEKeylifetimeHours.Duration.IsUnknown() {
			ike_keylifetime_hoursMap["duration"] = data.IKEKeylifetimeHours.Duration.ValueInt64()
		}
		apiResource.Spec["ike_keylifetime_hours"] = ike_keylifetime_hoursMap
	}
	if data.IKEKeylifetimeMinutes != nil {
		ike_keylifetime_minutesMap := make(map[string]interface{})
		if !data.IKEKeylifetimeMinutes.Duration.IsNull() && !data.IKEKeylifetimeMinutes.Duration.IsUnknown() {
			ike_keylifetime_minutesMap["duration"] = data.IKEKeylifetimeMinutes.Duration.ValueInt64()
		}
		apiResource.Spec["ike_keylifetime_minutes"] = ike_keylifetime_minutesMap
	}
	if data.ReauthDisabled != nil {
		reauth_disabledMap := make(map[string]interface{})
		apiResource.Spec["reauth_disabled"] = reauth_disabledMap
	}
	if data.ReauthTimeoutDays != nil {
		reauth_timeout_daysMap := make(map[string]interface{})
		if !data.ReauthTimeoutDays.Duration.IsNull() && !data.ReauthTimeoutDays.Duration.IsUnknown() {
			reauth_timeout_daysMap["duration"] = data.ReauthTimeoutDays.Duration.ValueInt64()
		}
		apiResource.Spec["reauth_timeout_days"] = reauth_timeout_daysMap
	}
	if data.ReauthTimeoutHours != nil {
		reauth_timeout_hoursMap := make(map[string]interface{})
		if !data.ReauthTimeoutHours.Duration.IsNull() && !data.ReauthTimeoutHours.Duration.IsUnknown() {
			reauth_timeout_hoursMap["duration"] = data.ReauthTimeoutHours.Duration.ValueInt64()
		}
		apiResource.Spec["reauth_timeout_hours"] = reauth_timeout_hoursMap
	}
	if data.UseDefaultKeylifetime != nil {
		use_default_keylifetimeMap := make(map[string]interface{})
		apiResource.Spec["use_default_keylifetime"] = use_default_keylifetimeMap
	}

	_, err := r.client.UpdateIKEPhase1Profile(ctx, apiResource)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update IKEPhase1Profile: %s", err))
		return
	}

	// Use plan data for ID since API response may not include metadata.name
	data.ID = types.StringValue(data.Name.ValueString())

	// Fetch the resource to get complete state including computed fields
	// PUT responses may not include all computed nested fields (like tenant in Object Reference blocks)
	fetched, fetchErr := r.client.GetIKEPhase1Profile(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if fetchErr != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read IKEPhase1Profile after update: %s", fetchErr))
		return
	}

	// Set computed fields from API response

	// Unmarshal spec fields from fetched resource to Terraform state
	apiResource = fetched // Use GET response which includes all computed fields
	isImport := false     // Update is never an import
	_ = isImport          // May be unused if resource has no blocks needing import detection
	if v, ok := apiResource.Spec["authentication_algos"].([]interface{}); ok && len(v) > 0 {
		var authentication_algosList []string
		for _, item := range v {
			if s, ok := item.(string); ok {
				authentication_algosList = append(authentication_algosList, s)
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.StringType, authentication_algosList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.AuthenticationAlgos = listVal
		}
	} else {
		data.AuthenticationAlgos = types.ListNull(types.StringType)
	}
	if v, ok := apiResource.Spec["dh_group"].([]interface{}); ok && len(v) > 0 {
		var dh_groupList []string
		for _, item := range v {
			if s, ok := item.(string); ok {
				dh_groupList = append(dh_groupList, s)
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.StringType, dh_groupList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.DhGroup = listVal
		}
	} else {
		data.DhGroup = types.ListNull(types.StringType)
	}
	if v, ok := apiResource.Spec["encryption_algos"].([]interface{}); ok && len(v) > 0 {
		var encryption_algosList []string
		for _, item := range v {
			if s, ok := item.(string); ok {
				encryption_algosList = append(encryption_algosList, s)
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.StringType, encryption_algosList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.EncryptionAlgos = listVal
		}
	} else {
		data.EncryptionAlgos = types.ListNull(types.StringType)
	}
	if v, ok := apiResource.Spec["prf"].([]interface{}); ok && len(v) > 0 {
		var prfList []string
		for _, item := range v {
			if s, ok := item.(string); ok {
				prfList = append(prfList, s)
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.StringType, prfList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Prf = listVal
		}
	} else {
		data.Prf = types.ListNull(types.StringType)
	}
	if blockData, ok := apiResource.Spec["ike_keylifetime_hours"].(map[string]interface{}); ok && (isImport || data.IKEKeylifetimeHours != nil) {
		data.IKEKeylifetimeHours = &IKEPhase1ProfileIKEKeylifetimeHoursModel{
			Duration: func() types.Int64 {
				if !isImport && data.IKEKeylifetimeHours != nil {
					// Preserve existing state (null or user-set value)
					// This prevents API defaults (like 0) from overwriting user intent
					return data.IKEKeylifetimeHours.Duration
				}
				if !isImport {
					// Block not in user config - return null, not API default
					return types.Int64Null()
				}
				// Import case: read from API
				if v, ok := blockData["duration"].(float64); ok {
					return types.Int64Value(int64(v))
				}
				return types.Int64Null()
			}(),
		}
	}
	if blockData, ok := apiResource.Spec["ike_keylifetime_minutes"].(map[string]interface{}); ok && (isImport || data.IKEKeylifetimeMinutes != nil) {
		data.IKEKeylifetimeMinutes = &IKEPhase1ProfileIKEKeylifetimeMinutesModel{
			Duration: func() types.Int64 {
				if !isImport && data.IKEKeylifetimeMinutes != nil {
					// Preserve existing state (null or user-set value)
					// This prevents API defaults (like 0) from overwriting user intent
					return data.IKEKeylifetimeMinutes.Duration
				}
				if !isImport {
					// Block not in user config - return null, not API default
					return types.Int64Null()
				}
				// Import case: read from API
				if v, ok := blockData["duration"].(float64); ok {
					return types.Int64Value(int64(v))
				}
				return types.Int64Null()
			}(),
		}
	}
	if _, ok := apiResource.Spec["reauth_disabled"].(map[string]interface{}); ok && isImport && data.ReauthDisabled == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.ReauthDisabled = &IKEPhase1ProfileEmptyModel{}
	}
	// Normal Read: preserve existing state value
	if blockData, ok := apiResource.Spec["reauth_timeout_days"].(map[string]interface{}); ok && (isImport || data.ReauthTimeoutDays != nil) {
		data.ReauthTimeoutDays = &IKEPhase1ProfileReauthTimeoutDaysModel{
			Duration: func() types.Int64 {
				if !isImport && data.ReauthTimeoutDays != nil {
					// Preserve existing state (null or user-set value)
					// This prevents API defaults (like 0) from overwriting user intent
					return data.ReauthTimeoutDays.Duration
				}
				if !isImport {
					// Block not in user config - return null, not API default
					return types.Int64Null()
				}
				// Import case: read from API
				if v, ok := blockData["duration"].(float64); ok {
					return types.Int64Value(int64(v))
				}
				return types.Int64Null()
			}(),
		}
	}
	if blockData, ok := apiResource.Spec["reauth_timeout_hours"].(map[string]interface{}); ok && (isImport || data.ReauthTimeoutHours != nil) {
		data.ReauthTimeoutHours = &IKEPhase1ProfileReauthTimeoutHoursModel{
			Duration: func() types.Int64 {
				if !isImport && data.ReauthTimeoutHours != nil {
					// Preserve existing state (null or user-set value)
					// This prevents API defaults (like 0) from overwriting user intent
					return data.ReauthTimeoutHours.Duration
				}
				if !isImport {
					// Block not in user config - return null, not API default
					return types.Int64Null()
				}
				// Import case: read from API
				if v, ok := blockData["duration"].(float64); ok {
					return types.Int64Value(int64(v))
				}
				return types.Int64Null()
			}(),
		}
	}
	if _, ok := apiResource.Spec["use_default_keylifetime"].(map[string]interface{}); ok && isImport && data.UseDefaultKeylifetime == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.UseDefaultKeylifetime = &IKEPhase1ProfileEmptyModel{}
	}
	// Normal Read: preserve existing state value

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *IKEPhase1ProfileResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data IKEPhase1ProfileResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	deleteTimeout, diags := data.Timeouts.Delete(ctx, inttimeouts.DefaultDelete)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, deleteTimeout)
	defer cancel()
	err := r.client.DeleteIKEPhase1Profile(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		// If the resource is already gone, consider deletion successful (idempotent delete)
		if strings.Contains(err.Error(), "NOT_FOUND") || strings.Contains(err.Error(), "404") {
			tflog.Warn(ctx, "IKEPhase1Profile already deleted, removing from state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			return
		}
		// If delete is not implemented (501), warn and remove from state
		// Some F5 XC resources don't support deletion via API
		if strings.Contains(err.Error(), "501") {
			tflog.Warn(ctx, "IKEPhase1Profile delete not supported by API (501), removing from state only", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete IKEPhase1Profile: %s", err))
		return
	}
}

func (r *IKEPhase1ProfileResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import ID format: namespace/name
	parts := strings.Split(req.ID, "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError(
			"Invalid Import ID",
			fmt.Sprintf("Expected import ID format: namespace/name, got: %s", req.ID),
		)
		return
	}
	namespace := parts[0]
	name := parts[1]

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("namespace"), namespace)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), name)...)

	// Set private state marker to indicate this is an import operation
	// This allows Read to populate all nested blocks from API response
	diags := resp.Private.SetKey(ctx, "isImport", []byte("true"))
	resp.Diagnostics.Append(diags...)
}
