// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/f5xc-salesdemos/terraform-provider-f5xc/internal/client"
	inttimeouts "github.com/f5xc-salesdemos/terraform-provider-f5xc/internal/timeouts"
	"github.com/f5xc-salesdemos/terraform-provider-f5xc/internal/validators"
)

// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource                   = &IKEPhase2ProfileResource{}
	_ resource.ResourceWithConfigure      = &IKEPhase2ProfileResource{}
	_ resource.ResourceWithImportState    = &IKEPhase2ProfileResource{}
	_ resource.ResourceWithModifyPlan     = &IKEPhase2ProfileResource{}
	_ resource.ResourceWithValidateConfig = &IKEPhase2ProfileResource{}
)

func NewIKEPhase2ProfileResource() resource.Resource {
	return &IKEPhase2ProfileResource{}
}

type IKEPhase2ProfileResource struct {
	client *client.Client
}

// IKEPhase2ProfileEmptyModel represents empty nested blocks
type IKEPhase2ProfileEmptyModel struct {
}

// IKEPhase2ProfileDhGroupSetModel represents dh_group_set block
type IKEPhase2ProfileDhGroupSetModel struct {
	DhGroups types.List `tfsdk:"dh_groups"`
}

// IKEPhase2ProfileDhGroupSetModelAttrTypes defines the attribute types for IKEPhase2ProfileDhGroupSetModel
var IKEPhase2ProfileDhGroupSetModelAttrTypes = map[string]attr.Type{
	"dh_groups": types.ListType{ElemType: types.StringType},
}

// IKEPhase2ProfileIKEKeylifetimeHoursModel represents ike_keylifetime_hours block
type IKEPhase2ProfileIKEKeylifetimeHoursModel struct {
	Duration types.Int64 `tfsdk:"duration"`
}

// IKEPhase2ProfileIKEKeylifetimeHoursModelAttrTypes defines the attribute types for IKEPhase2ProfileIKEKeylifetimeHoursModel
var IKEPhase2ProfileIKEKeylifetimeHoursModelAttrTypes = map[string]attr.Type{
	"duration": types.Int64Type,
}

// IKEPhase2ProfileIKEKeylifetimeMinutesModel represents ike_keylifetime_minutes block
type IKEPhase2ProfileIKEKeylifetimeMinutesModel struct {
	Duration types.Int64 `tfsdk:"duration"`
}

// IKEPhase2ProfileIKEKeylifetimeMinutesModelAttrTypes defines the attribute types for IKEPhase2ProfileIKEKeylifetimeMinutesModel
var IKEPhase2ProfileIKEKeylifetimeMinutesModelAttrTypes = map[string]attr.Type{
	"duration": types.Int64Type,
}

type IKEPhase2ProfileResourceModel struct {
	Name                  types.String                                `tfsdk:"name"`
	Namespace             types.String                                `tfsdk:"namespace"`
	AuthenticationAlgos   types.List                                  `tfsdk:"authentication_algos"`
	EncryptionAlgos       types.List                                  `tfsdk:"encryption_algos"`
	Annotations           types.Map                                   `tfsdk:"annotations"`
	Description           types.String                                `tfsdk:"description"`
	Disable               types.Bool                                  `tfsdk:"disable"`
	Labels                types.Map                                   `tfsdk:"labels"`
	ID                    types.String                                `tfsdk:"id"`
	Timeouts              timeouts.Value                              `tfsdk:"timeouts"`
	DhGroupSet            *IKEPhase2ProfileDhGroupSetModel            `tfsdk:"dh_group_set"`
	DisablePfs            *IKEPhase2ProfileEmptyModel                 `tfsdk:"disable_pfs"`
	IKEKeylifetimeHours   *IKEPhase2ProfileIKEKeylifetimeHoursModel   `tfsdk:"ike_keylifetime_hours"`
	IKEKeylifetimeMinutes *IKEPhase2ProfileIKEKeylifetimeMinutesModel `tfsdk:"ike_keylifetime_minutes"`
	UseDefaultKeylifetime *IKEPhase2ProfileEmptyModel                 `tfsdk:"use_default_keylifetime"`
}

func (r *IKEPhase2ProfileResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_ike_phase2_profile"
}

func (r *IKEPhase2ProfileResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a IKE Phase2 Profile resource in F5 Distributed Cloud for ike phase2 profile specification. configuration.",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				MarkdownDescription: "Name of the IKE Phase2 Profile. Must be unique within the namespace.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.NameValidator(),
				},
			},
			"namespace": schema.StringAttribute{
				MarkdownDescription: "Namespace where the IKE Phase2 Profile will be created.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.NamespaceValidator(),
				},
			},
			"authentication_algos": schema.ListAttribute{
				MarkdownDescription: "[Enum: AUTH_ALG_DEFAULT|SHA256_HMAC|SHA384_HMAC|SHA512_HMAC|AUTH_ALG_NONE] Choose one or more Authentication Algorithm. Use None option when using the aes-gcm or aes-ccm encryption algorithms. Possible values are `AUTH_ALG_DEFAULT`, `SHA256_HMAC`, `SHA384_HMAC`, `SHA512_HMAC`, `AUTH_ALG_NONE`. Defaults to `AUTH_ALG_DEFAULT`.",
				Required:            true,
				ElementType:         types.StringType,
			},
			"encryption_algos": schema.ListAttribute{
				MarkdownDescription: "[Enum: ENC_ALG_DEFAULT|AES128_CBC|AES192_CBC|AES256_CBC|TRIPLE_DES_CBC|AES128_GCM|AES192_GCM|AES256_GCM] Choose one or more encryption algorithms. Possible values are `ENC_ALG_DEFAULT`, `AES128_CBC`, `AES192_CBC`, `AES256_CBC`, `TRIPLE_DES_CBC`, `AES128_GCM`, `AES192_GCM`, `AES256_GCM`. Defaults to `ENC_ALG_DEFAULT`.",
				Required:            true,
				ElementType:         types.StringType,
			},
			"annotations": schema.MapAttribute{
				MarkdownDescription: "Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Human readable description for the object.",
				Optional:            true,
			},
			"disable": schema.BoolAttribute{
				MarkdownDescription: "A value of true will administratively disable the object.",
				Optional:            true,
			},
			"labels": schema.MapAttribute{
				MarkdownDescription: "Labels is a user defined key value map that can be attached to resources for organization and filtering.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier for the resource.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
		Blocks: map[string]schema.Block{
			"timeouts": timeouts.Block(ctx, timeouts.Opts{
				Create: true,
				Read:   true,
				Update: true,
				Delete: true,
			}),
			"dh_group_set": schema.SingleNestedBlock{
				MarkdownDescription: "[OneOf: dh_group_set, disable_pfs; Default: disable_pfs] Choose the acceptable Diffie Hellman(DH) Group or Groups that you are willing to accept as part of this profile.",
				Attributes: map[string]schema.Attribute{
					"dh_groups": schema.ListAttribute{
						MarkdownDescription: "[Enum: DH_GROUP_DEFAULT|DH_GROUP_14|DH_GROUP_15|DH_GROUP_16|DH_GROUP_17|DH_GROUP_18|DH_GROUP_19|DH_GROUP_20|DH_GROUP_21|DH_GROUP_26] Choose the acceptable Diffie Hellman(DH) Group or Groups that you are willing to accept as part of this profile. Possible values are `DH_GROUP_DEFAULT`, `DH_GROUP_14`, `DH_GROUP_15`, `DH_GROUP_16`, `DH_GROUP_17`, `DH_GROUP_18`, `DH_GROUP_19`, `DH_GROUP_20`, `DH_GROUP_21`, `DH_GROUP_26`. Defaults to `DH_GROUP_DEFAULT`.",
						Optional:            true,
						ElementType:         types.StringType,
					},
				},
			},
			"disable_pfs": schema.SingleNestedBlock{
				MarkdownDescription: "Configuration parameter for disable pfs.",
			},
			"ike_keylifetime_hours": schema.SingleNestedBlock{
				MarkdownDescription: "[OneOf: ike_keylifetime_hours, ike_keylifetime_minutes, use_default_keylifetime; Default: use_default_keylifetime] Configuration parameter for ike keylifetime hours.",
				Attributes: map[string]schema.Attribute{
					"duration": schema.Int64Attribute{
						MarkdownDescription: "Duration. Configuration parameter for duration",
						Optional:            true,
					},
				},
			},
			"ike_keylifetime_minutes": schema.SingleNestedBlock{
				MarkdownDescription: "Configuration parameter for ike keylifetime minutes.",
				Attributes: map[string]schema.Attribute{
					"duration": schema.Int64Attribute{
						MarkdownDescription: "Duration. Configuration parameter for duration",
						Optional:            true,
					},
				},
			},
			"use_default_keylifetime": schema.SingleNestedBlock{
				MarkdownDescription: "Configuration parameter for use default keylifetime.",
			},
		},
	}
}

func (r *IKEPhase2ProfileResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.client = client
}

// ValidateConfig implements resource.ResourceWithValidateConfig
func (r *IKEPhase2ProfileResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var data IKEPhase2ProfileResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
}

// ModifyPlan implements resource.ResourceWithModifyPlan
func (r *IKEPhase2ProfileResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() {
		resp.Diagnostics.AddWarning(
			"Resource Destruction",
			"This will permanently delete the ike_phase2_profile from F5 Distributed Cloud.",
		)
		return
	}

	if req.State.Raw.IsNull() {
		var plan IKEPhase2ProfileResourceModel
		resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
		if resp.Diagnostics.HasError() {
			return
		}

		if plan.Name.IsUnknown() {
			resp.Diagnostics.AddWarning(
				"Unknown Resource Name",
				"The resource name is not yet known. This may affect planning for dependent resources.",
			)
		}
	}
}

func (r *IKEPhase2ProfileResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data IKEPhase2ProfileResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createTimeout, diags := data.Timeouts.Create(ctx, inttimeouts.DefaultCreate)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, createTimeout)
	defer cancel()

	tflog.Debug(ctx, "Creating ike_phase2_profile", map[string]interface{}{
		"name":      data.Name.ValueString(),
		"namespace": data.Namespace.ValueString(),
	})

	createReq := &client.IKEPhase2Profile{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: make(map[string]interface{}),
	}

	if !data.Description.IsNull() {
		createReq.Metadata.Description = data.Description.ValueString()
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.Metadata.Labels = labels
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.Metadata.Annotations = annotations
	}

	// Marshal spec fields from Terraform state to API struct
	if !data.AuthenticationAlgos.IsNull() && !data.AuthenticationAlgos.IsUnknown() {
		var authentication_algosList []string
		resp.Diagnostics.Append(data.AuthenticationAlgos.ElementsAs(ctx, &authentication_algosList, false)...)
		if !resp.Diagnostics.HasError() {
			createReq.Spec["authentication_algos"] = authentication_algosList
		}
	}
	if !data.EncryptionAlgos.IsNull() && !data.EncryptionAlgos.IsUnknown() {
		var encryption_algosList []string
		resp.Diagnostics.Append(data.EncryptionAlgos.ElementsAs(ctx, &encryption_algosList, false)...)
		if !resp.Diagnostics.HasError() {
			createReq.Spec["encryption_algos"] = encryption_algosList
		}
	}
	if data.DhGroupSet != nil {
		dh_group_setMap := make(map[string]interface{})
		if !data.DhGroupSet.DhGroups.IsNull() && !data.DhGroupSet.DhGroups.IsUnknown() {
			var dh_groupsItems []string
			diags := data.DhGroupSet.DhGroups.ElementsAs(ctx, &dh_groupsItems, false)
			if !diags.HasError() {
				dh_group_setMap["dh_groups"] = dh_groupsItems
			}
		}
		createReq.Spec["dh_group_set"] = dh_group_setMap
	}
	if data.DisablePfs != nil {
		disable_pfsMap := make(map[string]interface{})
		createReq.Spec["disable_pfs"] = disable_pfsMap
	}
	if data.IKEKeylifetimeHours != nil {
		ike_keylifetime_hoursMap := make(map[string]interface{})
		if !data.IKEKeylifetimeHours.Duration.IsNull() && !data.IKEKeylifetimeHours.Duration.IsUnknown() {
			ike_keylifetime_hoursMap["duration"] = data.IKEKeylifetimeHours.Duration.ValueInt64()
		}
		createReq.Spec["ike_keylifetime_hours"] = ike_keylifetime_hoursMap
	}
	if data.IKEKeylifetimeMinutes != nil {
		ike_keylifetime_minutesMap := make(map[string]interface{})
		if !data.IKEKeylifetimeMinutes.Duration.IsNull() && !data.IKEKeylifetimeMinutes.Duration.IsUnknown() {
			ike_keylifetime_minutesMap["duration"] = data.IKEKeylifetimeMinutes.Duration.ValueInt64()
		}
		createReq.Spec["ike_keylifetime_minutes"] = ike_keylifetime_minutesMap
	}
	if data.UseDefaultKeylifetime != nil {
		use_default_keylifetimeMap := make(map[string]interface{})
		createReq.Spec["use_default_keylifetime"] = use_default_keylifetimeMap
	}

	apiResource, err := r.client.CreateIKEPhase2Profile(ctx, createReq)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create IKEPhase2Profile: %s", err))
		return
	}

	data.ID = types.StringValue(apiResource.Metadata.Name)

	// Unmarshal spec fields from API response to Terraform state
	// This ensures computed nested fields (like tenant in Object Reference blocks) have known values
	isImport := false // Create is never an import
	_ = isImport      // May be unused if resource has no blocks needing import detection
	if v, ok := apiResource.Spec["authentication_algos"].([]interface{}); ok && len(v) > 0 {
		var authentication_algosList []string
		for _, item := range v {
			if s, ok := item.(string); ok {
				authentication_algosList = append(authentication_algosList, s)
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.StringType, authentication_algosList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.AuthenticationAlgos = listVal
		}
	} else {
		data.AuthenticationAlgos = types.ListNull(types.StringType)
	}
	if v, ok := apiResource.Spec["encryption_algos"].([]interface{}); ok && len(v) > 0 {
		var encryption_algosList []string
		for _, item := range v {
			if s, ok := item.(string); ok {
				encryption_algosList = append(encryption_algosList, s)
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.StringType, encryption_algosList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.EncryptionAlgos = listVal
		}
	} else {
		data.EncryptionAlgos = types.ListNull(types.StringType)
	}
	if blockData, ok := apiResource.Spec["dh_group_set"].(map[string]interface{}); ok && (isImport || data.DhGroupSet != nil) {
		data.DhGroupSet = &IKEPhase2ProfileDhGroupSetModel{
			DhGroups: func() types.List {
				if v, ok := blockData["dh_groups"].([]interface{}); ok && len(v) > 0 {
					var items []string
					for _, item := range v {
						if s, ok := item.(string); ok {
							items = append(items, s)
						}
					}
					listVal, _ := types.ListValueFrom(ctx, types.StringType, items)
					return listVal
				}
				return types.ListNull(types.StringType)
			}(),
		}
	}
	if _, ok := apiResource.Spec["disable_pfs"].(map[string]interface{}); ok && isImport && data.DisablePfs == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.DisablePfs = &IKEPhase2ProfileEmptyModel{}
	}
	// Normal Read: preserve existing state value
	if blockData, ok := apiResource.Spec["ike_keylifetime_hours"].(map[string]interface{}); ok && (isImport || data.IKEKeylifetimeHours != nil) {
		data.IKEKeylifetimeHours = &IKEPhase2ProfileIKEKeylifetimeHoursModel{
			Duration: func() types.Int64 {
				if !isImport && data.IKEKeylifetimeHours != nil {
					// Preserve existing state (null or user-set value)
					// This prevents API defaults (like 0) from overwriting user intent
					return data.IKEKeylifetimeHours.Duration
				}
				if !isImport {
					// Block not in user config - return null, not API default
					return types.Int64Null()
				}
				// Import case: read from API
				if v, ok := blockData["duration"].(float64); ok {
					return types.Int64Value(int64(v))
				}
				return types.Int64Null()
			}(),
		}
	}
	if blockData, ok := apiResource.Spec["ike_keylifetime_minutes"].(map[string]interface{}); ok && (isImport || data.IKEKeylifetimeMinutes != nil) {
		data.IKEKeylifetimeMinutes = &IKEPhase2ProfileIKEKeylifetimeMinutesModel{
			Duration: func() types.Int64 {
				if !isImport && data.IKEKeylifetimeMinutes != nil {
					// Preserve existing state (null or user-set value)
					// This prevents API defaults (like 0) from overwriting user intent
					return data.IKEKeylifetimeMinutes.Duration
				}
				if !isImport {
					// Block not in user config - return null, not API default
					return types.Int64Null()
				}
				// Import case: read from API
				if v, ok := blockData["duration"].(float64); ok {
					return types.Int64Value(int64(v))
				}
				return types.Int64Null()
			}(),
		}
	}
	if _, ok := apiResource.Spec["use_default_keylifetime"].(map[string]interface{}); ok && isImport && data.UseDefaultKeylifetime == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.UseDefaultKeylifetime = &IKEPhase2ProfileEmptyModel{}
	}
	// Normal Read: preserve existing state value

	tflog.Trace(ctx, "created IKEPhase2Profile resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *IKEPhase2ProfileResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data IKEPhase2ProfileResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	readTimeout, diags := data.Timeouts.Read(ctx, inttimeouts.DefaultRead)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, readTimeout)
	defer cancel()

	apiResource, err := r.client.GetIKEPhase2Profile(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		// Check if the resource was deleted outside Terraform
		if strings.Contains(err.Error(), "NOT_FOUND") || strings.Contains(err.Error(), "404") {
			tflog.Warn(ctx, "IKEPhase2Profile not found, removing from state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read IKEPhase2Profile: %s", err))
		return
	}

	data.ID = types.StringValue(apiResource.Metadata.Name)
	data.Name = types.StringValue(apiResource.Metadata.Name)
	data.Namespace = types.StringValue(apiResource.Metadata.Namespace)

	// Read description from metadata
	if apiResource.Metadata.Description != "" {
		data.Description = types.StringValue(apiResource.Metadata.Description)
	} else {
		data.Description = types.StringNull()
	}

	// Filter out system-managed labels (ves.io/*) that are injected by the platform
	if len(apiResource.Metadata.Labels) > 0 {
		filteredLabels := filterSystemLabels(apiResource.Metadata.Labels)
		if len(filteredLabels) > 0 {
			labels, diags := types.MapValueFrom(ctx, types.StringType, filteredLabels)
			resp.Diagnostics.Append(diags...)
			if !resp.Diagnostics.HasError() {
				data.Labels = labels
			}
		} else {
			data.Labels = types.MapNull(types.StringType)
		}
	} else {
		data.Labels = types.MapNull(types.StringType)
	}

	if len(apiResource.Metadata.Annotations) > 0 {
		annotations, diags := types.MapValueFrom(ctx, types.StringType, apiResource.Metadata.Annotations)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Annotations = annotations
		}
	} else {
		data.Annotations = types.MapNull(types.StringType)
	}

	// Check if this Read is triggered by an import operation
	// Import sets a private state marker so we know to populate all nested blocks from API response
	isImport := false
	if importMarker, diags := req.Private.GetKey(ctx, "isImport"); diags.HasError() == false && string(importMarker) == "true" {
		isImport = true
	}
	_ = isImport // May be unused if resource has no blocks needing import detection
	if v, ok := apiResource.Spec["authentication_algos"].([]interface{}); ok && len(v) > 0 {
		var authentication_algosList []string
		for _, item := range v {
			if s, ok := item.(string); ok {
				authentication_algosList = append(authentication_algosList, s)
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.StringType, authentication_algosList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.AuthenticationAlgos = listVal
		}
	} else {
		data.AuthenticationAlgos = types.ListNull(types.StringType)
	}
	if v, ok := apiResource.Spec["encryption_algos"].([]interface{}); ok && len(v) > 0 {
		var encryption_algosList []string
		for _, item := range v {
			if s, ok := item.(string); ok {
				encryption_algosList = append(encryption_algosList, s)
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.StringType, encryption_algosList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.EncryptionAlgos = listVal
		}
	} else {
		data.EncryptionAlgos = types.ListNull(types.StringType)
	}
	if blockData, ok := apiResource.Spec["dh_group_set"].(map[string]interface{}); ok && (isImport || data.DhGroupSet != nil) {
		data.DhGroupSet = &IKEPhase2ProfileDhGroupSetModel{
			DhGroups: func() types.List {
				if v, ok := blockData["dh_groups"].([]interface{}); ok && len(v) > 0 {
					var items []string
					for _, item := range v {
						if s, ok := item.(string); ok {
							items = append(items, s)
						}
					}
					listVal, _ := types.ListValueFrom(ctx, types.StringType, items)
					return listVal
				}
				return types.ListNull(types.StringType)
			}(),
		}
	}
	if _, ok := apiResource.Spec["disable_pfs"].(map[string]interface{}); ok && isImport && data.DisablePfs == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.DisablePfs = &IKEPhase2ProfileEmptyModel{}
	}
	// Normal Read: preserve existing state value
	if blockData, ok := apiResource.Spec["ike_keylifetime_hours"].(map[string]interface{}); ok && (isImport || data.IKEKeylifetimeHours != nil) {
		data.IKEKeylifetimeHours = &IKEPhase2ProfileIKEKeylifetimeHoursModel{
			Duration: func() types.Int64 {
				if !isImport && data.IKEKeylifetimeHours != nil {
					// Preserve existing state (null or user-set value)
					// This prevents API defaults (like 0) from overwriting user intent
					return data.IKEKeylifetimeHours.Duration
				}
				if !isImport {
					// Block not in user config - return null, not API default
					return types.Int64Null()
				}
				// Import case: read from API
				if v, ok := blockData["duration"].(float64); ok {
					return types.Int64Value(int64(v))
				}
				return types.Int64Null()
			}(),
		}
	}
	if blockData, ok := apiResource.Spec["ike_keylifetime_minutes"].(map[string]interface{}); ok && (isImport || data.IKEKeylifetimeMinutes != nil) {
		data.IKEKeylifetimeMinutes = &IKEPhase2ProfileIKEKeylifetimeMinutesModel{
			Duration: func() types.Int64 {
				if !isImport && data.IKEKeylifetimeMinutes != nil {
					// Preserve existing state (null or user-set value)
					// This prevents API defaults (like 0) from overwriting user intent
					return data.IKEKeylifetimeMinutes.Duration
				}
				if !isImport {
					// Block not in user config - return null, not API default
					return types.Int64Null()
				}
				// Import case: read from API
				if v, ok := blockData["duration"].(float64); ok {
					return types.Int64Value(int64(v))
				}
				return types.Int64Null()
			}(),
		}
	}
	if _, ok := apiResource.Spec["use_default_keylifetime"].(map[string]interface{}); ok && isImport && data.UseDefaultKeylifetime == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.UseDefaultKeylifetime = &IKEPhase2ProfileEmptyModel{}
	}
	// Normal Read: preserve existing state value

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *IKEPhase2ProfileResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data IKEPhase2ProfileResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	updateTimeout, diags := data.Timeouts.Update(ctx, inttimeouts.DefaultUpdate)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, updateTimeout)
	defer cancel()

	apiResource := &client.IKEPhase2Profile{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: make(map[string]interface{}),
	}

	if !data.Description.IsNull() {
		apiResource.Metadata.Description = data.Description.ValueString()
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Labels = labels
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Annotations = annotations
	}

	// Marshal spec fields from Terraform state to API struct
	if !data.AuthenticationAlgos.IsNull() && !data.AuthenticationAlgos.IsUnknown() {
		var authentication_algosList []string
		resp.Diagnostics.Append(data.AuthenticationAlgos.ElementsAs(ctx, &authentication_algosList, false)...)
		if !resp.Diagnostics.HasError() {
			apiResource.Spec["authentication_algos"] = authentication_algosList
		}
	}
	if !data.EncryptionAlgos.IsNull() && !data.EncryptionAlgos.IsUnknown() {
		var encryption_algosList []string
		resp.Diagnostics.Append(data.EncryptionAlgos.ElementsAs(ctx, &encryption_algosList, false)...)
		if !resp.Diagnostics.HasError() {
			apiResource.Spec["encryption_algos"] = encryption_algosList
		}
	}
	if data.DhGroupSet != nil {
		dh_group_setMap := make(map[string]interface{})
		if !data.DhGroupSet.DhGroups.IsNull() && !data.DhGroupSet.DhGroups.IsUnknown() {
			var dh_groupsItems []string
			diags := data.DhGroupSet.DhGroups.ElementsAs(ctx, &dh_groupsItems, false)
			if !diags.HasError() {
				dh_group_setMap["dh_groups"] = dh_groupsItems
			}
		}
		apiResource.Spec["dh_group_set"] = dh_group_setMap
	}
	if data.DisablePfs != nil {
		disable_pfsMap := make(map[string]interface{})
		apiResource.Spec["disable_pfs"] = disable_pfsMap
	}
	if data.IKEKeylifetimeHours != nil {
		ike_keylifetime_hoursMap := make(map[string]interface{})
		if !data.IKEKeylifetimeHours.Duration.IsNull() && !data.IKEKeylifetimeHours.Duration.IsUnknown() {
			ike_keylifetime_hoursMap["duration"] = data.IKEKeylifetimeHours.Duration.ValueInt64()
		}
		apiResource.Spec["ike_keylifetime_hours"] = ike_keylifetime_hoursMap
	}
	if data.IKEKeylifetimeMinutes != nil {
		ike_keylifetime_minutesMap := make(map[string]interface{})
		if !data.IKEKeylifetimeMinutes.Duration.IsNull() && !data.IKEKeylifetimeMinutes.Duration.IsUnknown() {
			ike_keylifetime_minutesMap["duration"] = data.IKEKeylifetimeMinutes.Duration.ValueInt64()
		}
		apiResource.Spec["ike_keylifetime_minutes"] = ike_keylifetime_minutesMap
	}
	if data.UseDefaultKeylifetime != nil {
		use_default_keylifetimeMap := make(map[string]interface{})
		apiResource.Spec["use_default_keylifetime"] = use_default_keylifetimeMap
	}

	_, err := r.client.UpdateIKEPhase2Profile(ctx, apiResource)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update IKEPhase2Profile: %s", err))
		return
	}

	// Use plan data for ID since API response may not include metadata.name
	data.ID = types.StringValue(data.Name.ValueString())

	// Fetch the resource to get complete state including computed fields
	// PUT responses may not include all computed nested fields (like tenant in Object Reference blocks)
	fetched, fetchErr := r.client.GetIKEPhase2Profile(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if fetchErr != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read IKEPhase2Profile after update: %s", fetchErr))
		return
	}

	// Set computed fields from API response

	// Unmarshal spec fields from fetched resource to Terraform state
	apiResource = fetched // Use GET response which includes all computed fields
	isImport := false     // Update is never an import
	_ = isImport          // May be unused if resource has no blocks needing import detection
	if v, ok := apiResource.Spec["authentication_algos"].([]interface{}); ok && len(v) > 0 {
		var authentication_algosList []string
		for _, item := range v {
			if s, ok := item.(string); ok {
				authentication_algosList = append(authentication_algosList, s)
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.StringType, authentication_algosList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.AuthenticationAlgos = listVal
		}
	} else {
		data.AuthenticationAlgos = types.ListNull(types.StringType)
	}
	if v, ok := apiResource.Spec["encryption_algos"].([]interface{}); ok && len(v) > 0 {
		var encryption_algosList []string
		for _, item := range v {
			if s, ok := item.(string); ok {
				encryption_algosList = append(encryption_algosList, s)
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.StringType, encryption_algosList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.EncryptionAlgos = listVal
		}
	} else {
		data.EncryptionAlgos = types.ListNull(types.StringType)
	}
	if blockData, ok := apiResource.Spec["dh_group_set"].(map[string]interface{}); ok && (isImport || data.DhGroupSet != nil) {
		data.DhGroupSet = &IKEPhase2ProfileDhGroupSetModel{
			DhGroups: func() types.List {
				if v, ok := blockData["dh_groups"].([]interface{}); ok && len(v) > 0 {
					var items []string
					for _, item := range v {
						if s, ok := item.(string); ok {
							items = append(items, s)
						}
					}
					listVal, _ := types.ListValueFrom(ctx, types.StringType, items)
					return listVal
				}
				return types.ListNull(types.StringType)
			}(),
		}
	}
	if _, ok := apiResource.Spec["disable_pfs"].(map[string]interface{}); ok && isImport && data.DisablePfs == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.DisablePfs = &IKEPhase2ProfileEmptyModel{}
	}
	// Normal Read: preserve existing state value
	if blockData, ok := apiResource.Spec["ike_keylifetime_hours"].(map[string]interface{}); ok && (isImport || data.IKEKeylifetimeHours != nil) {
		data.IKEKeylifetimeHours = &IKEPhase2ProfileIKEKeylifetimeHoursModel{
			Duration: func() types.Int64 {
				if !isImport && data.IKEKeylifetimeHours != nil {
					// Preserve existing state (null or user-set value)
					// This prevents API defaults (like 0) from overwriting user intent
					return data.IKEKeylifetimeHours.Duration
				}
				if !isImport {
					// Block not in user config - return null, not API default
					return types.Int64Null()
				}
				// Import case: read from API
				if v, ok := blockData["duration"].(float64); ok {
					return types.Int64Value(int64(v))
				}
				return types.Int64Null()
			}(),
		}
	}
	if blockData, ok := apiResource.Spec["ike_keylifetime_minutes"].(map[string]interface{}); ok && (isImport || data.IKEKeylifetimeMinutes != nil) {
		data.IKEKeylifetimeMinutes = &IKEPhase2ProfileIKEKeylifetimeMinutesModel{
			Duration: func() types.Int64 {
				if !isImport && data.IKEKeylifetimeMinutes != nil {
					// Preserve existing state (null or user-set value)
					// This prevents API defaults (like 0) from overwriting user intent
					return data.IKEKeylifetimeMinutes.Duration
				}
				if !isImport {
					// Block not in user config - return null, not API default
					return types.Int64Null()
				}
				// Import case: read from API
				if v, ok := blockData["duration"].(float64); ok {
					return types.Int64Value(int64(v))
				}
				return types.Int64Null()
			}(),
		}
	}
	if _, ok := apiResource.Spec["use_default_keylifetime"].(map[string]interface{}); ok && isImport && data.UseDefaultKeylifetime == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.UseDefaultKeylifetime = &IKEPhase2ProfileEmptyModel{}
	}
	// Normal Read: preserve existing state value

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *IKEPhase2ProfileResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data IKEPhase2ProfileResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	deleteTimeout, diags := data.Timeouts.Delete(ctx, inttimeouts.DefaultDelete)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, deleteTimeout)
	defer cancel()
	err := r.client.DeleteIKEPhase2Profile(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		// If the resource is already gone, consider deletion successful (idempotent delete)
		if strings.Contains(err.Error(), "NOT_FOUND") || strings.Contains(err.Error(), "404") {
			tflog.Warn(ctx, "IKEPhase2Profile already deleted, removing from state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			return
		}
		// If delete is not implemented (501), warn and remove from state
		// Some F5 XC resources don't support deletion via API
		if strings.Contains(err.Error(), "501") {
			tflog.Warn(ctx, "IKEPhase2Profile delete not supported by API (501), removing from state only", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete IKEPhase2Profile: %s", err))
		return
	}
}

func (r *IKEPhase2ProfileResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import ID format: namespace/name
	parts := strings.Split(req.ID, "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError(
			"Invalid Import ID",
			fmt.Sprintf("Expected import ID format: namespace/name, got: %s", req.ID),
		)
		return
	}
	namespace := parts[0]
	name := parts[1]

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("namespace"), namespace)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), name)...)

	// Set private state marker to indicate this is an import operation
	// This allows Read to populate all nested blocks from API response
	diags := resp.Private.SetKey(ctx, "isImport", []byte("true"))
	resp.Diagnostics.Append(diags...)
}
