// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification — read-only data source (GetSpecType only)

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/f5xc-salesdemos/terraform-provider-xcsh/internal/client"
)

var (
	_ datasource.DataSource              = &LmaRegionDataSource{}
	_ datasource.DataSourceWithConfigure = &LmaRegionDataSource{}
)

func NewLmaRegionDataSource() datasource.DataSource {
	return &LmaRegionDataSource{}
}

type LmaRegionDataSource struct {
	client *client.Client
}

type LmaRegionDataSourceModel struct {
	ID               types.String `tfsdk:"id"`
	Name             types.String `tfsdk:"name"`
	Namespace        types.String `tfsdk:"namespace"`
	Description      types.String `tfsdk:"description"`
	Labels           types.Map    `tfsdk:"labels"`
	Annotations      types.Map    `tfsdk:"annotations"`
	AWSParams        types.String `tfsdk:"aws_params"`
	ClickhouseParams types.String `tfsdk:"clickhouse_params"`
	ElasticParams    types.String `tfsdk:"elastic_params"`
	IsDefault        types.String `tfsdk:"is_default"`
	KafkaParams      types.String `tfsdk:"kafka_params"`
}

func (d *LmaRegionDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_lma_region"
}

func (d *LmaRegionDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a Lma Region resource in F5 Distributed Cloud for lma region specification. configuration. (read-only data source)",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier.",
				Computed:            true,
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "Name of the LmaRegion to look up.",
				Required:            true,
			},
			"namespace": schema.StringAttribute{
				MarkdownDescription: "Namespace of the LmaRegion.",
				Required:            true,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Description.",
				Computed:            true,
			},
			"labels": schema.MapAttribute{
				MarkdownDescription: "Labels.",
				Computed:            true,
				ElementType:         types.StringType,
			},
			"annotations": schema.MapAttribute{
				MarkdownDescription: "Annotations.",
				Computed:            true,
				ElementType:         types.StringType,
			},
			"aws_params": schema.StringAttribute{
				MarkdownDescription: "AWS Params. AWS parameters.",
				Computed:            true,
			},
			"clickhouse_params": schema.StringAttribute{
				MarkdownDescription: "Configuration parameter for clickhouse params.",
				Computed:            true,
			},
			"elastic_params": schema.StringAttribute{
				MarkdownDescription: "Configuration parameter for elastic params.",
				Computed:            true,
			},
			"is_default": schema.StringAttribute{
				MarkdownDescription: "Is Default. Is this the default region.",
				Computed:            true,
			},
			"kafka_params": schema.StringAttribute{
				MarkdownDescription: "Configuration parameter for kafka params.",
				Computed:            true,
			},
		},
	}
}

func (d *LmaRegionDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Data Source Configure Type", "Expected *client.Client")
		return
	}
	d.client = client
}

func (d *LmaRegionDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data LmaRegionDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resource, err := d.client.GetLmaRegion(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read LmaRegion: %s", err))
		return
	}

	data.ID = types.StringValue(resource.Metadata.Name)
	data.Name = types.StringValue(resource.Metadata.Name)
	data.Namespace = types.StringValue(resource.Metadata.Namespace)
	if resource.Metadata.Description != "" {
		data.Description = types.StringValue(resource.Metadata.Description)
	} else {
		data.Description = types.StringNull()
	}

	if len(resource.Metadata.Labels) > 0 {
		filteredLabels := filterSystemLabels(resource.Metadata.Labels)
		if len(filteredLabels) > 0 {
			labels, diags := types.MapValueFrom(ctx, types.StringType, filteredLabels)
			resp.Diagnostics.Append(diags...)
			if !resp.Diagnostics.HasError() {
				data.Labels = labels
			}
		} else {
			data.Labels = types.MapNull(types.StringType)
		}
	} else {
		data.Labels = types.MapNull(types.StringType)
	}

	if len(resource.Metadata.Annotations) > 0 {
		annotations, diags := types.MapValueFrom(ctx, types.StringType, resource.Metadata.Annotations)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Annotations = annotations
		}
	} else {
		data.Annotations = types.MapNull(types.StringType)
	}

	// Map spec fields from API response
	if v, ok := resource.Spec["aws_params"]; ok && v != nil {
		data.AWSParams = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.AWSParams = types.StringNull()
	}
	if v, ok := resource.Spec["clickhouse_params"]; ok && v != nil {
		data.ClickhouseParams = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.ClickhouseParams = types.StringNull()
	}
	if v, ok := resource.Spec["elastic_params"]; ok && v != nil {
		data.ElasticParams = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.ElasticParams = types.StringNull()
	}
	if v, ok := resource.Spec["is_default"]; ok && v != nil {
		data.IsDefault = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.IsDefault = types.StringNull()
	}
	if v, ok := resource.Spec["kafka_params"]; ok && v != nil {
		data.KafkaParams = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.KafkaParams = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
