// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification — read-only data source (GetSpecType only)

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/f5xc-salesdemos/terraform-provider-xcsh/internal/client"
)

var (
	_ datasource.DataSource              = &NginxCsgDataSource{}
	_ datasource.DataSourceWithConfigure = &NginxCsgDataSource{}
)

func NewNginxCsgDataSource() datasource.DataSource {
	return &NginxCsgDataSource{}
}

type NginxCsgDataSource struct {
	client *client.Client
}

type NginxCsgDataSourceModel struct {
	ID               types.String `tfsdk:"id"`
	Name             types.String `tfsdk:"name"`
	Namespace        types.String `tfsdk:"namespace"`
	Description      types.String `tfsdk:"description"`
	Labels           types.Map    `tfsdk:"labels"`
	Annotations      types.Map    `tfsdk:"annotations"`
	APIDiscoverySpec types.String `tfsdk:"api_discovery_spec"`
	CsgName          types.String `tfsdk:"csg_name"`
	ObjectID         types.String `tfsdk:"object_id"`
	WAFSpec          types.String `tfsdk:"waf_spec"`
}

func (d *NginxCsgDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_nginx_csg"
}

func (d *NginxCsgDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a Nginx Csg resource in F5 Distributed Cloud for get nginx csg configuration. configuration. (read-only data source)",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier.",
				Computed:            true,
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "Name of the NginxCsg to look up.",
				Required:            true,
			},
			"namespace": schema.StringAttribute{
				MarkdownDescription: "Namespace of the NginxCsg.",
				Required:            true,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Description.",
				Computed:            true,
			},
			"labels": schema.MapAttribute{
				MarkdownDescription: "Labels.",
				Computed:            true,
				ElementType:         types.StringType,
			},
			"annotations": schema.MapAttribute{
				MarkdownDescription: "Annotations.",
				Computed:            true,
				ElementType:         types.StringType,
			},
			"api_discovery_spec": schema.StringAttribute{
				MarkdownDescription: "Configuration for api_discovery_spec.",
				Computed:            true,
			},
			"csg_name": schema.StringAttribute{
				MarkdownDescription: "CSGName. Name for CSG in NGINX One.",
				Computed:            true,
			},
			"object_id": schema.StringAttribute{
				MarkdownDescription: "Identifier for config sync group in NGINX One.",
				Computed:            true,
			},
			"waf_spec": schema.StringAttribute{
				MarkdownDescription: "Configuration for waf_spec.",
				Computed:            true,
			},
		},
	}
}

func (d *NginxCsgDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Data Source Configure Type", "Expected *client.Client")
		return
	}
	d.client = client
}

func (d *NginxCsgDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data NginxCsgDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resource, err := d.client.GetNginxCsg(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read NginxCsg: %s", err))
		return
	}

	data.ID = types.StringValue(resource.Metadata.Name)
	data.Name = types.StringValue(resource.Metadata.Name)
	data.Namespace = types.StringValue(resource.Metadata.Namespace)
	if resource.Metadata.Description != "" {
		data.Description = types.StringValue(resource.Metadata.Description)
	} else {
		data.Description = types.StringNull()
	}

	if len(resource.Metadata.Labels) > 0 {
		filteredLabels := filterSystemLabels(resource.Metadata.Labels)
		if len(filteredLabels) > 0 {
			labels, diags := types.MapValueFrom(ctx, types.StringType, filteredLabels)
			resp.Diagnostics.Append(diags...)
			if !resp.Diagnostics.HasError() {
				data.Labels = labels
			}
		} else {
			data.Labels = types.MapNull(types.StringType)
		}
	} else {
		data.Labels = types.MapNull(types.StringType)
	}

	if len(resource.Metadata.Annotations) > 0 {
		annotations, diags := types.MapValueFrom(ctx, types.StringType, resource.Metadata.Annotations)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Annotations = annotations
		}
	} else {
		data.Annotations = types.MapNull(types.StringType)
	}

	// Map spec fields from API response
	if v, ok := resource.Spec["api_discovery_spec"]; ok && v != nil {
		data.APIDiscoverySpec = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.APIDiscoverySpec = types.StringNull()
	}
	if v, ok := resource.Spec["csg_name"]; ok && v != nil {
		data.CsgName = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.CsgName = types.StringNull()
	}
	if v, ok := resource.Spec["object_id"]; ok && v != nil {
		data.ObjectID = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.ObjectID = types.StringNull()
	}
	if v, ok := resource.Spec["waf_spec"]; ok && v != nil {
		data.WAFSpec = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.WAFSpec = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
