// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification — read-only data source (GetSpecType only)

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/f5xc-salesdemos/terraform-provider-f5xc/internal/client"
)

var (
	_ datasource.DataSource              = &NginxServerDataSource{}
	_ datasource.DataSourceWithConfigure = &NginxServerDataSource{}
)

func NewNginxServerDataSource() datasource.DataSource {
	return &NginxServerDataSource{}
}

type NginxServerDataSource struct {
	client *client.Client
}

type NginxServerDataSourceModel struct {
	ID           types.String `tfsdk:"id"`
	Name         types.String `tfsdk:"name"`
	Namespace    types.String `tfsdk:"namespace"`
	Description  types.String `tfsdk:"description"`
	Labels       types.Map    `tfsdk:"labels"`
	Annotations  types.Map    `tfsdk:"annotations"`
	DataplaneRef types.String `tfsdk:"dataplane_ref"`
	ServerSpec   types.String `tfsdk:"server_spec"`
}

func (d *NginxServerDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_nginx_server"
}

func (d *NginxServerDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a Nginx Server resource in F5 Distributed Cloud for get nginx server block configuration. configuration. (read-only data source)",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier.",
				Computed:            true,
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "Name of the NginxServer to look up.",
				Required:            true,
			},
			"namespace": schema.StringAttribute{
				MarkdownDescription: "Namespace of the NginxServer.",
				Required:            true,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Description.",
				Computed:            true,
			},
			"labels": schema.MapAttribute{
				MarkdownDescription: "Labels.",
				Computed:            true,
				ElementType:         types.StringType,
			},
			"annotations": schema.MapAttribute{
				MarkdownDescription: "Annotations.",
				Computed:            true,
				ElementType:         types.StringType,
			},
			"dataplane_ref": schema.StringAttribute{
				MarkdownDescription: "DataplaneReference.",
				Computed:            true,
			},
			"server_spec": schema.StringAttribute{
				MarkdownDescription: "Configuration for server_spec.",
				Computed:            true,
			},
		},
	}
}

func (d *NginxServerDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Data Source Configure Type", "Expected *client.Client")
		return
	}
	d.client = client
}

func (d *NginxServerDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data NginxServerDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resource, err := d.client.GetNginxServer(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read NginxServer: %s", err))
		return
	}

	data.ID = types.StringValue(resource.Metadata.Name)
	data.Name = types.StringValue(resource.Metadata.Name)
	data.Namespace = types.StringValue(resource.Metadata.Namespace)
	if resource.Metadata.Description != "" {
		data.Description = types.StringValue(resource.Metadata.Description)
	} else {
		data.Description = types.StringNull()
	}

	if len(resource.Metadata.Labels) > 0 {
		filteredLabels := filterSystemLabels(resource.Metadata.Labels)
		if len(filteredLabels) > 0 {
			labels, diags := types.MapValueFrom(ctx, types.StringType, filteredLabels)
			resp.Diagnostics.Append(diags...)
			if !resp.Diagnostics.HasError() {
				data.Labels = labels
			}
		} else {
			data.Labels = types.MapNull(types.StringType)
		}
	} else {
		data.Labels = types.MapNull(types.StringType)
	}

	if len(resource.Metadata.Annotations) > 0 {
		annotations, diags := types.MapValueFrom(ctx, types.StringType, resource.Metadata.Annotations)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Annotations = annotations
		}
	} else {
		data.Annotations = types.MapNull(types.StringType)
	}

	// Map spec fields from API response
	if v, ok := resource.Spec["dataplane_ref"]; ok && v != nil {
		data.DataplaneRef = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.DataplaneRef = types.StringNull()
	}
	if v, ok := resource.Spec["server_spec"]; ok && v != nil {
		data.ServerSpec = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.ServerSpec = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
