// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/f5xc-salesdemos/terraform-provider-f5xc/internal/client"
	inttimeouts "github.com/f5xc-salesdemos/terraform-provider-f5xc/internal/timeouts"
	"github.com/f5xc-salesdemos/terraform-provider-f5xc/internal/validators"
)

// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource                   = &Srv6NetworkSliceResource{}
	_ resource.ResourceWithConfigure      = &Srv6NetworkSliceResource{}
	_ resource.ResourceWithImportState    = &Srv6NetworkSliceResource{}
	_ resource.ResourceWithModifyPlan     = &Srv6NetworkSliceResource{}
	_ resource.ResourceWithValidateConfig = &Srv6NetworkSliceResource{}
)

func NewSrv6NetworkSliceResource() resource.Resource {
	return &Srv6NetworkSliceResource{}
}

type Srv6NetworkSliceResource struct {
	client *client.Client
}

type Srv6NetworkSliceResourceModel struct {
	Name                        types.String   `tfsdk:"name"`
	Namespace                   types.String   `tfsdk:"namespace"`
	SidPrefixes                 types.List     `tfsdk:"sid_prefixes"`
	Annotations                 types.Map      `tfsdk:"annotations"`
	Description                 types.String   `tfsdk:"description"`
	Disable                     types.Bool     `tfsdk:"disable"`
	Labels                      types.Map      `tfsdk:"labels"`
	ID                          types.String   `tfsdk:"id"`
	ConnectToAccessNetworks     types.Bool     `tfsdk:"connect_to_access_networks"`
	ConnectToEnterpriseNetworks types.Bool     `tfsdk:"connect_to_enterprise_networks"`
	ConnectToInternet           types.Bool     `tfsdk:"connect_to_internet"`
	Timeouts                    timeouts.Value `tfsdk:"timeouts"`
}

func (r *Srv6NetworkSliceResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_srv6_network_slice"
}

func (r *Srv6NetworkSliceResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages srv6_network_slice creates a new object in the storage backend for metadata.namespace. in F5 Distributed Cloud.",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				MarkdownDescription: "Name of the Srv6 Network Slice. Must be unique within the namespace.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.NameValidator(),
				},
			},
			"namespace": schema.StringAttribute{
				MarkdownDescription: "Namespace where the Srv6 Network Slice will be created.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.NamespaceValidator(),
				},
			},
			"sid_prefixes": schema.ListAttribute{
				MarkdownDescription: "SID Locator from the prefix is allocated automatically for each node in each site.",
				Required:            true,
				ElementType:         types.StringType,
				Validators: []validator.List{
					listvalidator.SizeBetween(1, 1),
				},
			},
			"annotations": schema.MapAttribute{
				MarkdownDescription: "Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Human readable description for the object.",
				Optional:            true,
			},
			"disable": schema.BoolAttribute{
				MarkdownDescription: "A value of true will administratively disable the object.",
				Optional:            true,
			},
			"labels": schema.MapAttribute{
				MarkdownDescription: "Labels is a user defined key value map that can be attached to resources for organization and filtering.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier for the resource.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"connect_to_access_networks": schema.BoolAttribute{
				MarkdownDescription: "Connect all SRv6 Virtual Networks in this slice to their corresponding access networks by importing route targets specified in the virtual network.",
				Required:            true,
			},
			"connect_to_enterprise_networks": schema.BoolAttribute{
				MarkdownDescription: "Connect all SRv6 Virtual Networks in this slice to their corresponding enterprise networks by importing route targets specified in the virtual network.",
				Required:            true,
			},
			"connect_to_internet": schema.BoolAttribute{
				MarkdownDescription: "Connect all SRv6 Virtual Networks in this slice to the Internet by importing route targets specified in the virtual network.",
				Required:            true,
			},
		},
		Blocks: map[string]schema.Block{
			"timeouts": timeouts.Block(ctx, timeouts.Opts{
				Create: true,
				Read:   true,
				Update: true,
				Delete: true,
			}),
		},
	}
}

func (r *Srv6NetworkSliceResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.client = client
}

// ValidateConfig implements resource.ResourceWithValidateConfig
func (r *Srv6NetworkSliceResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var data Srv6NetworkSliceResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
}

// ModifyPlan implements resource.ResourceWithModifyPlan
func (r *Srv6NetworkSliceResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() {
		resp.Diagnostics.AddWarning(
			"Resource Destruction",
			"This will permanently delete the srv6_network_slice from F5 Distributed Cloud.",
		)
		return
	}

	if req.State.Raw.IsNull() {
		var plan Srv6NetworkSliceResourceModel
		resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
		if resp.Diagnostics.HasError() {
			return
		}

		if plan.Name.IsUnknown() {
			resp.Diagnostics.AddWarning(
				"Unknown Resource Name",
				"The resource name is not yet known. This may affect planning for dependent resources.",
			)
		}
	}
}

func (r *Srv6NetworkSliceResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data Srv6NetworkSliceResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createTimeout, diags := data.Timeouts.Create(ctx, inttimeouts.DefaultCreate)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, createTimeout)
	defer cancel()

	tflog.Debug(ctx, "Creating srv6_network_slice", map[string]interface{}{
		"name":      data.Name.ValueString(),
		"namespace": data.Namespace.ValueString(),
	})

	createReq := &client.Srv6NetworkSlice{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: make(map[string]interface{}),
	}

	if !data.Description.IsNull() {
		createReq.Metadata.Description = data.Description.ValueString()
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.Metadata.Labels = labels
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.Metadata.Annotations = annotations
	}

	// Marshal spec fields from Terraform state to API struct
	if !data.SidPrefixes.IsNull() && !data.SidPrefixes.IsUnknown() {
		var sid_prefixesList []string
		resp.Diagnostics.Append(data.SidPrefixes.ElementsAs(ctx, &sid_prefixesList, false)...)
		if !resp.Diagnostics.HasError() {
			createReq.Spec["sid_prefixes"] = sid_prefixesList
		}
	}
	if !data.ConnectToAccessNetworks.IsNull() && !data.ConnectToAccessNetworks.IsUnknown() {
		createReq.Spec["connect_to_access_networks"] = data.ConnectToAccessNetworks.ValueBool()
	}
	if !data.ConnectToEnterpriseNetworks.IsNull() && !data.ConnectToEnterpriseNetworks.IsUnknown() {
		createReq.Spec["connect_to_enterprise_networks"] = data.ConnectToEnterpriseNetworks.ValueBool()
	}
	if !data.ConnectToInternet.IsNull() && !data.ConnectToInternet.IsUnknown() {
		createReq.Spec["connect_to_internet"] = data.ConnectToInternet.ValueBool()
	}

	apiResource, err := r.client.CreateSrv6NetworkSlice(ctx, createReq)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create Srv6NetworkSlice: %s", err))
		return
	}

	data.ID = types.StringValue(apiResource.Metadata.Name)

	// Unmarshal spec fields from API response to Terraform state
	// This ensures computed nested fields (like tenant in Object Reference blocks) have known values
	isImport := false // Create is never an import
	_ = isImport      // May be unused if resource has no blocks needing import detection
	if v, ok := apiResource.Spec["sid_prefixes"].([]interface{}); ok && len(v) > 0 {
		var sid_prefixesList []string
		for _, item := range v {
			if s, ok := item.(string); ok {
				sid_prefixesList = append(sid_prefixesList, s)
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.StringType, sid_prefixesList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.SidPrefixes = listVal
		}
	} else {
		data.SidPrefixes = types.ListNull(types.StringType)
	}
	if v, ok := apiResource.Spec["connect_to_access_networks"].(bool); ok {
		data.ConnectToAccessNetworks = types.BoolValue(v)
	} else {
		data.ConnectToAccessNetworks = types.BoolNull()
	}
	if v, ok := apiResource.Spec["connect_to_enterprise_networks"].(bool); ok {
		data.ConnectToEnterpriseNetworks = types.BoolValue(v)
	} else {
		data.ConnectToEnterpriseNetworks = types.BoolNull()
	}
	if v, ok := apiResource.Spec["connect_to_internet"].(bool); ok {
		data.ConnectToInternet = types.BoolValue(v)
	} else {
		data.ConnectToInternet = types.BoolNull()
	}

	tflog.Trace(ctx, "created Srv6NetworkSlice resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *Srv6NetworkSliceResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data Srv6NetworkSliceResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	readTimeout, diags := data.Timeouts.Read(ctx, inttimeouts.DefaultRead)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, readTimeout)
	defer cancel()

	apiResource, err := r.client.GetSrv6NetworkSlice(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		// Check if the resource was deleted outside Terraform
		if strings.Contains(err.Error(), "NOT_FOUND") || strings.Contains(err.Error(), "404") {
			tflog.Warn(ctx, "Srv6NetworkSlice not found, removing from state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read Srv6NetworkSlice: %s", err))
		return
	}

	data.ID = types.StringValue(apiResource.Metadata.Name)
	data.Name = types.StringValue(apiResource.Metadata.Name)
	data.Namespace = types.StringValue(apiResource.Metadata.Namespace)

	// Read description from metadata
	if apiResource.Metadata.Description != "" {
		data.Description = types.StringValue(apiResource.Metadata.Description)
	} else {
		data.Description = types.StringNull()
	}

	// Filter out system-managed labels (ves.io/*) that are injected by the platform
	if len(apiResource.Metadata.Labels) > 0 {
		filteredLabels := filterSystemLabels(apiResource.Metadata.Labels)
		if len(filteredLabels) > 0 {
			labels, diags := types.MapValueFrom(ctx, types.StringType, filteredLabels)
			resp.Diagnostics.Append(diags...)
			if !resp.Diagnostics.HasError() {
				data.Labels = labels
			}
		} else {
			data.Labels = types.MapNull(types.StringType)
		}
	} else {
		data.Labels = types.MapNull(types.StringType)
	}

	if len(apiResource.Metadata.Annotations) > 0 {
		annotations, diags := types.MapValueFrom(ctx, types.StringType, apiResource.Metadata.Annotations)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Annotations = annotations
		}
	} else {
		data.Annotations = types.MapNull(types.StringType)
	}

	// Check if this Read is triggered by an import operation
	// Import sets a private state marker so we know to populate all nested blocks from API response
	isImport := false
	if importMarker, diags := req.Private.GetKey(ctx, "isImport"); diags.HasError() == false && string(importMarker) == "true" {
		isImport = true
	}
	_ = isImport // May be unused if resource has no blocks needing import detection
	if v, ok := apiResource.Spec["sid_prefixes"].([]interface{}); ok && len(v) > 0 {
		var sid_prefixesList []string
		for _, item := range v {
			if s, ok := item.(string); ok {
				sid_prefixesList = append(sid_prefixesList, s)
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.StringType, sid_prefixesList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.SidPrefixes = listVal
		}
	} else {
		data.SidPrefixes = types.ListNull(types.StringType)
	}
	if v, ok := apiResource.Spec["connect_to_access_networks"].(bool); ok {
		data.ConnectToAccessNetworks = types.BoolValue(v)
	} else {
		data.ConnectToAccessNetworks = types.BoolNull()
	}
	if v, ok := apiResource.Spec["connect_to_enterprise_networks"].(bool); ok {
		data.ConnectToEnterpriseNetworks = types.BoolValue(v)
	} else {
		data.ConnectToEnterpriseNetworks = types.BoolNull()
	}
	if v, ok := apiResource.Spec["connect_to_internet"].(bool); ok {
		data.ConnectToInternet = types.BoolValue(v)
	} else {
		data.ConnectToInternet = types.BoolNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *Srv6NetworkSliceResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data Srv6NetworkSliceResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	updateTimeout, diags := data.Timeouts.Update(ctx, inttimeouts.DefaultUpdate)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, updateTimeout)
	defer cancel()

	apiResource := &client.Srv6NetworkSlice{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: make(map[string]interface{}),
	}

	if !data.Description.IsNull() {
		apiResource.Metadata.Description = data.Description.ValueString()
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Labels = labels
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Annotations = annotations
	}

	// Marshal spec fields from Terraform state to API struct
	if !data.SidPrefixes.IsNull() && !data.SidPrefixes.IsUnknown() {
		var sid_prefixesList []string
		resp.Diagnostics.Append(data.SidPrefixes.ElementsAs(ctx, &sid_prefixesList, false)...)
		if !resp.Diagnostics.HasError() {
			apiResource.Spec["sid_prefixes"] = sid_prefixesList
		}
	}
	if !data.ConnectToAccessNetworks.IsNull() && !data.ConnectToAccessNetworks.IsUnknown() {
		apiResource.Spec["connect_to_access_networks"] = data.ConnectToAccessNetworks.ValueBool()
	}
	if !data.ConnectToEnterpriseNetworks.IsNull() && !data.ConnectToEnterpriseNetworks.IsUnknown() {
		apiResource.Spec["connect_to_enterprise_networks"] = data.ConnectToEnterpriseNetworks.ValueBool()
	}
	if !data.ConnectToInternet.IsNull() && !data.ConnectToInternet.IsUnknown() {
		apiResource.Spec["connect_to_internet"] = data.ConnectToInternet.ValueBool()
	}

	_, err := r.client.UpdateSrv6NetworkSlice(ctx, apiResource)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update Srv6NetworkSlice: %s", err))
		return
	}

	// Use plan data for ID since API response may not include metadata.name
	data.ID = types.StringValue(data.Name.ValueString())

	// Fetch the resource to get complete state including computed fields
	// PUT responses may not include all computed nested fields (like tenant in Object Reference blocks)
	fetched, fetchErr := r.client.GetSrv6NetworkSlice(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if fetchErr != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read Srv6NetworkSlice after update: %s", fetchErr))
		return
	}

	// Set computed fields from API response

	// Unmarshal spec fields from fetched resource to Terraform state
	apiResource = fetched // Use GET response which includes all computed fields
	isImport := false     // Update is never an import
	_ = isImport          // May be unused if resource has no blocks needing import detection
	if v, ok := apiResource.Spec["sid_prefixes"].([]interface{}); ok && len(v) > 0 {
		var sid_prefixesList []string
		for _, item := range v {
			if s, ok := item.(string); ok {
				sid_prefixesList = append(sid_prefixesList, s)
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.StringType, sid_prefixesList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.SidPrefixes = listVal
		}
	} else {
		data.SidPrefixes = types.ListNull(types.StringType)
	}
	if v, ok := apiResource.Spec["connect_to_access_networks"].(bool); ok {
		data.ConnectToAccessNetworks = types.BoolValue(v)
	} else {
		data.ConnectToAccessNetworks = types.BoolNull()
	}
	if v, ok := apiResource.Spec["connect_to_enterprise_networks"].(bool); ok {
		data.ConnectToEnterpriseNetworks = types.BoolValue(v)
	} else {
		data.ConnectToEnterpriseNetworks = types.BoolNull()
	}
	if v, ok := apiResource.Spec["connect_to_internet"].(bool); ok {
		data.ConnectToInternet = types.BoolValue(v)
	} else {
		data.ConnectToInternet = types.BoolNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *Srv6NetworkSliceResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data Srv6NetworkSliceResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	deleteTimeout, diags := data.Timeouts.Delete(ctx, inttimeouts.DefaultDelete)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, deleteTimeout)
	defer cancel()
	err := r.client.DeleteSrv6NetworkSlice(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		// If the resource is already gone, consider deletion successful (idempotent delete)
		if strings.Contains(err.Error(), "NOT_FOUND") || strings.Contains(err.Error(), "404") {
			tflog.Warn(ctx, "Srv6NetworkSlice already deleted, removing from state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			return
		}
		// If delete is not implemented (501), warn and remove from state
		// Some F5 XC resources don't support deletion via API
		if strings.Contains(err.Error(), "501") {
			tflog.Warn(ctx, "Srv6NetworkSlice delete not supported by API (501), removing from state only", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete Srv6NetworkSlice: %s", err))
		return
	}
}

func (r *Srv6NetworkSliceResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import ID format: namespace/name
	parts := strings.Split(req.ID, "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError(
			"Invalid Import ID",
			fmt.Sprintf("Expected import ID format: namespace/name, got: %s", req.ID),
		)
		return
	}
	namespace := parts[0]
	name := parts[1]

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("namespace"), namespace)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), name)...)

	// Set private state marker to indicate this is an import operation
	// This allows Read to populate all nested blocks from API response
	diags := resp.Private.SetKey(ctx, "isImport", []byte("true"))
	resp.Diagnostics.Append(diags...)
}
