// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification — read-only data source (GetSpecType only)

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/f5xc-salesdemos/terraform-provider-f5xc/internal/client"
)

var (
	_ datasource.DataSource              = &ThirdPartyApplicationDataSource{}
	_ datasource.DataSourceWithConfigure = &ThirdPartyApplicationDataSource{}
)

func NewThirdPartyApplicationDataSource() datasource.DataSource {
	return &ThirdPartyApplicationDataSource{}
}

type ThirdPartyApplicationDataSource struct {
	client *client.Client
}

type ThirdPartyApplicationDataSourceModel struct {
	ID                         types.String `tfsdk:"id"`
	Name                       types.String `tfsdk:"name"`
	Namespace                  types.String `tfsdk:"namespace"`
	Description                types.String `tfsdk:"description"`
	Labels                     types.Map    `tfsdk:"labels"`
	Annotations                types.Map    `tfsdk:"annotations"`
	APISpecification           types.String `tfsdk:"api_specification"`
	DefaultSensitiveDataPolicy types.String `tfsdk:"default_sensitive_data_policy"`
	DisableAPIDefinition       types.String `tfsdk:"disable_api_definition"`
	DisableAPIDiscovery        types.String `tfsdk:"disable_api_discovery"`
	EnableAPIDiscovery         types.String `tfsdk:"enable_api_discovery"`
	SensitiveDataPolicy        types.String `tfsdk:"sensitive_data_policy"`
	ServiceDiscovery           types.String `tfsdk:"service_discovery"`
}

func (d *ThirdPartyApplicationDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_third_party_application"
}

func (d *ThirdPartyApplicationDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a Third Party Application resource in F5 Distributed Cloud for third party application specification. configuration. (read-only data source)",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier.",
				Computed:            true,
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "Name of the ThirdPartyApplication to look up.",
				Required:            true,
			},
			"namespace": schema.StringAttribute{
				MarkdownDescription: "Namespace of the ThirdPartyApplication.",
				Required:            true,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Description.",
				Computed:            true,
			},
			"labels": schema.MapAttribute{
				MarkdownDescription: "Labels.",
				Computed:            true,
				ElementType:         types.StringType,
			},
			"annotations": schema.MapAttribute{
				MarkdownDescription: "Annotations.",
				Computed:            true,
				ElementType:         types.StringType,
			},
			"api_specification": schema.StringAttribute{
				MarkdownDescription: "Settings for API specification (API definition, OpenAPI validation, etc.).",
				Computed:            true,
			},
			"default_sensitive_data_policy": schema.StringAttribute{
				MarkdownDescription: "Policy configuration for this feature.",
				Computed:            true,
			},
			"disable_api_definition": schema.StringAttribute{
				MarkdownDescription: "Enable this option",
				Computed:            true,
			},
			"disable_api_discovery": schema.StringAttribute{
				MarkdownDescription: "Enable this option",
				Computed:            true,
			},
			"enable_api_discovery": schema.StringAttribute{
				MarkdownDescription: "Specifies the settings used for API discovery.",
				Computed:            true,
			},
			"sensitive_data_policy": schema.StringAttribute{
				MarkdownDescription: "Policy configuration for this feature.",
				Computed:            true,
			},
			"service_discovery": schema.StringAttribute{
				MarkdownDescription: "Type establishes a direct reference from one object(the referrer) to another(the referred). Such a reference is in form of tenant/namespace/name.",
				Computed:            true,
			},
		},
	}
}

func (d *ThirdPartyApplicationDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Data Source Configure Type", "Expected *client.Client")
		return
	}
	d.client = client
}

func (d *ThirdPartyApplicationDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data ThirdPartyApplicationDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resource, err := d.client.GetThirdPartyApplication(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read ThirdPartyApplication: %s", err))
		return
	}

	data.ID = types.StringValue(resource.Metadata.Name)
	data.Name = types.StringValue(resource.Metadata.Name)
	data.Namespace = types.StringValue(resource.Metadata.Namespace)
	if resource.Metadata.Description != "" {
		data.Description = types.StringValue(resource.Metadata.Description)
	} else {
		data.Description = types.StringNull()
	}

	if len(resource.Metadata.Labels) > 0 {
		filteredLabels := filterSystemLabels(resource.Metadata.Labels)
		if len(filteredLabels) > 0 {
			labels, diags := types.MapValueFrom(ctx, types.StringType, filteredLabels)
			resp.Diagnostics.Append(diags...)
			if !resp.Diagnostics.HasError() {
				data.Labels = labels
			}
		} else {
			data.Labels = types.MapNull(types.StringType)
		}
	} else {
		data.Labels = types.MapNull(types.StringType)
	}

	if len(resource.Metadata.Annotations) > 0 {
		annotations, diags := types.MapValueFrom(ctx, types.StringType, resource.Metadata.Annotations)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Annotations = annotations
		}
	} else {
		data.Annotations = types.MapNull(types.StringType)
	}

	// Map spec fields from API response
	if v, ok := resource.Spec["api_specification"]; ok && v != nil {
		data.APISpecification = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.APISpecification = types.StringNull()
	}
	if v, ok := resource.Spec["default_sensitive_data_policy"]; ok && v != nil {
		data.DefaultSensitiveDataPolicy = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.DefaultSensitiveDataPolicy = types.StringNull()
	}
	if v, ok := resource.Spec["disable_api_definition"]; ok && v != nil {
		data.DisableAPIDefinition = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.DisableAPIDefinition = types.StringNull()
	}
	if v, ok := resource.Spec["disable_api_discovery"]; ok && v != nil {
		data.DisableAPIDiscovery = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.DisableAPIDiscovery = types.StringNull()
	}
	if v, ok := resource.Spec["enable_api_discovery"]; ok && v != nil {
		data.EnableAPIDiscovery = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.EnableAPIDiscovery = types.StringNull()
	}
	if v, ok := resource.Spec["sensitive_data_policy"]; ok && v != nil {
		data.SensitiveDataPolicy = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.SensitiveDataPolicy = types.StringNull()
	}
	if v, ok := resource.Spec["service_discovery"]; ok && v != nil {
		data.ServiceDiscovery = types.StringValue(fmt.Sprintf("%v", v))
	} else {
		data.ServiceDiscovery = types.StringNull()
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
